### ISSUE TITLE
[Bug] Crystalite Armor has animation bug with multiple players.

### ISSUE THREAD

**Issue by sylvxa** [quiqueck/BetterEnd#68] opened 2022-08-24 17:13 UTC
### What happened?

Crystalite Armor is not tied to the player who is wearing it, creating a weird animation bug when players are walking, running, sitting, etc. [Image of the bug here.](https://imgur.com/pWZ74fH) I've observed this on 1.19 versions as-well and suspect it's due to crystalite armor being overlaid on top of the player model instead of worn like vanilla armor.

### BetterEnd

1.1.1

### BCLib

1.4.7

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.18.2

**Comment by FalseJ** [comment] 2022-08-28 17:10
Yes! I wanna report this too! when there are multiple players on the screen, the crystalite armor (ESPECIALLY THE SHOES) will move with other people!

Here's the illustration:
![boots bug](https://user-images.githubusercontent.com/110573620/187086023-d1090064-daa6-4902-9277-742faa55927c.png)

I was running while my friend stand still, but his shoes are "running" and my shoes are "standing".
This also happened when player using "emoji mod" or view records in "replay mod"... but i guess these are the same problem?

BetterEnd
1.0.1 (edit: also in 1.0.3)

Minecraft
1.18.1

**Comment by quiqueck** [comment] 2022-10-08 18:54
Duplicate of #33

**Closed as completed by quiqueck** 2022-10-08 18:54 UTC
