### ISSUE TITLE
Crash at start up.

### ISSUE THREAD

**Issue by Sinogard** [quiqueck/BetterEnd#62] opened 2022-08-16 22:40 UTC
### What happened?

Crash at start up. Possible mod incompatibility with mythic metals.
log here https://paste.ee/p/Nb51t

### BetterEnd

2.0.11

### BCLib

2.0.20

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Other Mods

```shell
Mods:
  [✔️] 3dskinlayers-fabric-1.5.1-mc1.19.1
  [✔️] Adorn-3.6.1+1.19-fabric
  [✔️] architects-palette-fabric-2.1.1
  [✔️] architectury-6.2.43-fabric
  [✔️] bclib-2.0.20
  [✔️] BeaconOverhaul-1.7.2+1.19.1
  [✔️] better-end-2.0.11
  [✔️] betterf3-1.19.1-1.0
  [✔️] better-nether-7.0.9
  [✔️] BetterThirdPerson-Fabric-1.19-1.8.1
  [✔️] blockus-2.5.2+1.19.2
  [✔️] cloth-config-8.0.75-fabric
  [✔️] Clumps-forge-1.19.1-9.0.0+10
  [✔️] conjuring-1.0.25+1.19
  [✔️] convenient-mobgriefing-2.0.2
  [✔️] Decorative+Blocks-forge-1.18.2-2.1.0
  [✔️] DistantHorizons-1.6.9a-1.19.2
  [✔️] eden-ring-0.6.3
  [✔️] ellemes-container-library-2.0.1+1.19-fabric
  [✔️] elytraslot-fabric-6.0.0+1.19.2
  [✔️] enderscape-0.3.5-1.19.1
  [✔️] EquipmentCompare-1.19-fabric-1.3.1
  [✔️] expandedstorage-8.0.1+1.19-fabric
  [✔️] fabric-api-0.59.0+1.19.2
  [✔️] fabric-api-0.60.0+1.19.2
  [✔️] fabric-language-kotlin-1.8.2+kotlin.1.7.10
  [✔️] FallingTree-1.19.2-3.9.1
  [✔️] flesh2leather-1.0.3+1.19
  [✔️] ForgeConfigAPIPort-v4.1.4-1.19.1-Fabric
  [✔️] hookshot-26.0
  [✔️] Iceberg-1.19.1-fabric-1.0.46
  [✔️] illuminations-1.10.8
  [✔️] Incendium_v5.1.2
  [✔️] indium-1.0.7+mc1.19
  [✔️] inmis-2.7.0-1.19
  [✔️] InventoryHUD-fabric-[1.19.1]+-3.4.2
  [✔️] inventorysorter-1.19-20.0.0
  [✔️] iris-mc1.19.1-1.2.6
  [✔️] lambdynamiclights-2.1.2+1.19
  [✔️] LegendaryTooltips-1.19-fabric-1.2.6
  [✔️] light-overlay-7.0.0
  [✔️] logical_zoom-0.0.17
  [✔️] milkevsessentials-1.6.0
  [✔️] modmenu-4.0.6
  [✔️] moonlight-1.19-2.0.15
  [✔️] mythicmetals-0.15.3
  [✔️] NoCreativeDrift-1.19.2-3.0.0.0
  [✔️] no-enchant-cap-2.1.2+1.19.x
  [❌] Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7.jar (disabled)
  [✔️] owo-lib-0.7.3+1.19
  [✔️] Patchouli-1.19-74-FABRIC
  [✔️] randomblockplacement-1.19.1-forge42.0.1-1.1
  [✔️] replaymod-1.19.1-2.6.8
  [✔️] RoughlyEnoughItems-9.1.526
  [✔️] sodium-fabric-mc1.19-0.4.2 (replaymod compatible)
  [✔️] stacker-3.0.2-1.19.x
  [✔️] starlight-1.1.1+fabric.ae22326
  [✔️] supplementaries-1.19.2-2.0.13
  [❌] TerraBlender-fabric-1.19-2.0.0.117.jar (disabled)
  [❌] Terralith_v2.3.3.jar (disabled)
  [✔️] things-0.2.19+1.19
  [✔️] traverse-6.0.0-beta.1
  [✔️] trinkets-3.4.0
  [✔️] vanilla-hammers-3.4.1-custom-1.19
  [✔️] worldedit-mod-7.2.12
  [✔️] wraith-alloy-forgery-2.0.15+1.19
  [✔️] Xaeros_Minimap_22.13.0_Fabric_1.19.1
  [✔️] XaerosWorldMap_1.26.2_Fabric_1.19.1
  [✔️] zergatul.freecam-1.2.3-fabric-1.19.1
```

**Comment by quiqueck** [comment] 2022-08-17 01:28
Duplicate of quiqueck/BCLib#33

**Closed as completed by quiqueck** 2022-08-17 01:28 UTC
