### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thebebee** [quiqueck/BetterEnd#193] opened 2023-04-01 01:14 UTC
### What happened?

Upon entering the end the server / world would crash, to fix this I disabled the chorus forest. However now there's a new issue, there are no end cities. Using the /locate commands yields 0 responses.

### BetterEnd

2.1.4

### BCLib

2.1.6

### Fabric API

0.76.0

### Fabric Loader

0.14.17

### Minecraft

1.19.2

### Other Mods

```shell
Using the Wicked Witches SMP modpack
```

**Comment by begriefed** [comment] 2023-05-05 18:30
Duplicate of #188 

There is a link to a fixed version at the bottom of the comments.

**Closed as completed** 2023-06-19 22:17 UTC
