### ISSUE TITLE
[Bug] Compostable items on Fabric cannot be composted on Quilt.

### ISSUE THREAD

**Issue by SatDog92** [quiqueck/BetterEnd#95] opened 2022-10-13 16:51 UTC
### What happened?

**All** compostable items in Better End cannot be composted when using Quilt. Even when using REI, the recipes do not appear at all (the issue also happens without REI and its dependencies).

### BetterEnd

7.1.1

### BCLib

2.1.1

### Fabric API

Quilted Fabric API qfapi-4.0.0-beta.13_qsl-3.0.0-beta.16_fapi-0.62.0

### Fabric Loader

Quilt 0.17.5

### Minecraft

1.19.2

### Relevant log output

```shell
[18:40:21] [main/INFO]: Loading Minecraft 1.19.2 with Quilt Loader 0.17.5-beta.3
[18:40:22] [main/INFO]: Loading 85 mods:
| Index | Mod                                               | ID                                            | Version                      |
|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
|    71 | Architectury                                      | architectury                                  | 6.2.43                       |
|    40 | BCLib                                             | bclib                                         | 2.1.1                        |
|    81 | Better End                                        | betterend                                     | 2.1.1                        |
|    16 | Better Nether                                     | betternether                                  | 7.1.1                        |
|    73 | Cloth Config v8                                   | cloth-config                                  | 8.2.88                       |
|    56 | Error Notifier                                    | error_notifier                                | 1.0.9                        |
|    48 | Minecraft                                         | minecraft                                     | 1.19.2                       |
|    14 | OpenJDK 64-Bit Server VM                          | java                                          | 17                           |
|    82 | Quilt Advancement API                             | quilt_advancement                             | 3.0.0-beta.16+1.19.2         |
|    55 | Quilt Base API                                    | quilt_base                                    | 3.0.0-beta.16+1.19.2         |
|    80 | Quilt Biome API                                   | quilt_biome                                   | 3.0.0-beta.16+1.19.2         |
|    74 | Quilt Block Content Registry API                  | quilt_block_content_registry                  | 3.0.0-beta.16+1.19.2         |
|    49 | Quilt Block Entity API                            | quilt_block_entity                            | 3.0.0-beta.16+1.19.2         |
|    27 | Quilt Block Extensions API                        | quilt_block_extensions                        | 3.0.0-beta.16+1.19.2         |
|    79 | Quilt Client Command API                          | quilt_client_command                          | 3.0.0-beta.16+1.19.2         |
|    25 | Quilt Command API                                 | quilt_command                                 | 3.0.0-beta.16+1.19.2         |
|    76 | Quilt Crash Info                                  | quilt_crash_info                              | 3.0.0-beta.16+1.19.2         |
|    61 | Quilt DataFixerUpper API                          | quilt_datafixerupper                          | 3.0.0-beta.16+1.19.2         |
|    42 | Quilt Dimension API                               | quilt_dimension                               | 3.0.0-beta.16+1.19.2         |
|     8 | Quilt Item Content Registry API                   | quilt_item_content_registry                   | 3.0.0-beta.16+1.19.2         |
|    60 | Quilt Item Extension API                          | quilt_item_extension                          | 3.0.0-beta.16+1.19.2         |
|     9 | Quilt Item Group API                              | quilt_item_group                              | 3.0.0-beta.16+1.19.2         |
|     3 | Quilt Item Setting API                            | quilt_item_setting                            | 3.0.0-beta.16+1.19.2         |
|    57 | Quilt Lifecycle Events                            | quilt_lifecycle_events                        | 3.0.0-beta.16+1.19.2         |
|    83 | Quilt Loader                                      | quilt_loader                                  | 0.17.5-beta.3                |
|    17 | Quilt Multipart Entity API                        | quilt_entity_multipart                        | 3.0.0-beta.16+1.19.2         |
|    29 | Quilt Networking                                  | quilt_networking                              | 3.0.0-beta.16+1.19.2         |
|    36 | Quilt Recipe API                                  | quilt_recipe                                  | 3.0.0-beta.16+1.19.2         |
|    11 | Quilt Registry API                                | quilt_registry                                | 3.0.0-beta.16+1.19.2         |
|    72 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment               | 3.0.0-beta.16+1.19.2         |
|    19 | Quilt Resource Loader                             | quilt_resource_loader                         | 3.0.0-beta.16+1.19.2         |
|    15 | Quilt Screen API                                  | quilt_screen                                  | 3.0.0-beta.16+1.19.2         |
|    44 | Quilt Surface Rule API                            | quilt_surface_rule                            | 3.0.0-beta.16+1.19.2         |
|    20 | Quilt Tags API                                    | quilt_tags                                    | 3.0.0-beta.16+1.19.2         |
|    45 | Quilt Tooltip API                                 | quilt_tooltip                                 | 3.0.0-beta.16+1.19.2         |
|    31 | Quilted Fabric API                                | quilted_fabric_api                            | 4.0.0-beta.13+0.62.0-1.19.2  |
|    67 | Quilted Fabric API Base                           | quilted_fabric_api_base                       | 4.0.0-beta.13+0.62.0-1.19.2  |
|     6 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1              | 4.0.0-beta.13+0.62.0-1.19.2  |
|    63 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                   | 4.0.0-beta.13+0.62.0-1.19.2  |
|    77 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1            | 4.0.0-beta.13+0.62.0-1.19.2  |
|    75 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1             | 4.0.0-beta.13+0.62.0-1.19.2  |
|    37 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                 | 4.0.0-beta.13+0.62.0-1.19.2  |
|    41 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                 | 4.0.0-beta.13+0.62.0-1.19.2  |
|    33 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                    | 4.0.0-beta.13+0.62.0-1.19.2  |
|    53 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                  | 4.0.0-beta.13+0.62.0-1.19.2  |
|    68 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0          | 4.0.0-beta.13+0.62.0-1.19.2  |
|    52 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1         | 4.0.0-beta.13+0.62.0-1.19.2  |
|    23 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1           | 4.0.0-beta.13+0.62.0-1.19.2  |
|    78 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1         | 4.0.0-beta.13+0.62.0-1.19.2  |
|    34 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                  | 4.0.0-beta.13+0.62.0-1.19.2  |
|    54 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1               | 4.0.0-beta.13+0.62.0-1.19.2  |
|    43 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0          | 4.0.0-beta.13+0.62.0-1.19.2  |
|    66 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0            | 4.0.0-beta.13+0.62.0-1.19.2  |
|    28 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1               | 4.0.0-beta.13+0.62.0-1.19.2  |
|    59 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                    | 4.0.0-beta.13+0.62.0-1.19.2  |
|    12 | Quilted Fabric Item Groups (v0)                   | quilted_fabric_item_groups_v0                 | 4.0.0-beta.13+0.62.0-1.19.2  |
|    84 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1             | 4.0.0-beta.13+0.62.0-1.19.2  |
|    51 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                 | 4.0.0-beta.13+0.62.0-1.19.2  |
|     2 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1            | 4.0.0-beta.13+0.62.0-1.19.2  |
|    39 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                    | 4.0.0-beta.13+0.62.0-1.19.2  |
|     7 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                 | 4.0.0-beta.13+0.62.0-1.19.2  |
|    65 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                 | 4.0.0-beta.13+0.62.0-1.19.2  |
|    70 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1            | 4.0.0-beta.13+0.62.0-1.19.2  |
|    64 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                      | 4.0.0-beta.13+0.62.0-1.19.2  |
|    26 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                  | 4.0.0-beta.13+0.62.0-1.19.2  |
|    18 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1              | 4.0.0-beta.13+0.62.0-1.19.2  |
|    50 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1          | 4.0.0-beta.13+0.62.0-1.19.2  |
|    69 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                   | 4.0.0-beta.13+0.62.0-1.19.2  |
|    47 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0               | 4.0.0-beta.13+0.62.0-1.19.2  |
|     5 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                | 4.0.0-beta.13+0.62.0-1.19.2  |
|    13 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                | 4.0.0-beta.13+0.62.0-1.19.2  |
|    30 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1         | 4.0.0-beta.13+0.62.0-1.19.2  |
|    21 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                   | 4.0.0-beta.13+0.62.0-1.19.2  |
|    22 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                   | 4.0.0-beta.13+0.62.0-1.19.2  |
|    46 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1   | 4.0.0-beta.13+0.62.0-1.19.2  |
|    10 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1            | 4.0.0-beta.13+0.62.0-1.19.2  |
|    32 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1     | 4.0.0-beta.13+0.62.0-1.19.2  |
|    58 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0             | 4.0.0-beta.13+0.62.0-1.19.2  |
|    62 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                  | 4.0.0-beta.13+0.62.0-1.19.2  |
|    35 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1          | 4.0.0-beta.13+0.62.0-1.19.2  |
|    38 | Quilted Fabric Textures (v0)                      | quilted_fabric_textures_v0                    | 4.0.0-beta.13+0.62.0-1.19.2  |
|    24 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                | 4.0.0-beta.13+0.62.0-1.19.2  |
|     4 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1  | 4.0.0-beta.13+0.62.0-1.19.2  |
|     1 | Roughly Enough Items                              | roughlyenoughitems                            | 9.1.550                      |
|     0 | cloth-basic-math                                  | cloth-basic-math                              | 0.6.1                        |
|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
[18:40:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Utente/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Quilt Env=CLIENT
[18:40:23] [main/INFO]: Compatibility level set to JAVA_17
[18:40:28] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[18:40:28] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[18:40:28] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[18:40:28] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[18:40:30] [main/INFO]: Building optimized datafixer
[18:40:34] [main/INFO]: [Quilt Command] Networking support is enabled
[18:40:35] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[18:40:35] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[18:40:35] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[18:40:35] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[18:40:35] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[18:40:35] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[18:40:35] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[18:40:36] [main/WARN]: An unregistered entry on the Registry[ResourceKey[minecraft:root / minecraft:block] (Experimental)] registry was attempted to be registered in a content registry through the Quilted Fabric API bridge! Its instability will be circumvented through the activation of the registry's deferring queue, which may affect performance!
[18:40:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:40:38] [Render thread/INFO]: Setting user: SaturnoSomaro92
[18:40:38] [Render thread/INFO]: [REI] Config loaded
[18:40:38] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:request_tags_s2c
[18:40:39] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider REIPlugin [betterend] for REIPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[18:40:39] [Render thread/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[18:40:39] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[18:40:39] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[18:40:39] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[18:40:39] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[18:40:39] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[18:40:39] [Render thread/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[18:40:41] [Render thread/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[18:40:41] [Render thread/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[18:40:41] [Render thread/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[18:40:41] [Render thread/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[18:40:41] [Render thread/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[18:40:41] [Render thread/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[18:40:54] [Worker-Bootstrap-15/INFO]: 4283 Datafixer optimizations took 23765 milliseconds
[18:40:57] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIClientPlugin
[18:40:57] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIClientPlugin
[18:40:57] [Render thread/INFO]: [REI] Registered plugin provider REIPlugin [betterend] for REIClientPlugin
[18:40:57] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:ci_msg
[18:40:57] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:og_not_enough
[18:40:57] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[18:40:57] [Thread-2/INFO]: [bclib] Received Version Info for minecraft=1.19.2, loader=fabric
[18:40:57] [Thread-2/INFO]: [bclib]  - bclib:2.1.0
[18:40:57] [Thread-2/INFO]: [bclib]  - betterend:2.1.0
[18:40:57] [Thread-2/INFO]: [bclib]  - betternether:7.1.0
[18:40:57] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[18:40:57] [Render thread/INFO]: [Quilt Command|Client] Networking support is enabled
[18:40:58] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[18:40:58] [Render thread/WARN]: Removed resource pack Fabric Mods from options because it doesn't seem to exist anymore
[18:40:59] [Render thread/INFO]: Narrator library for x64 successfully loaded
[18:40:59] [Render thread/INFO]: Reloading ResourceManager: Default (Quilted Fabric Rendering Fluids (v1), Quilted Fabric Renderer - Indigo, Quilt Base API, Quilted Fabric Resource Loader (v0), Quilted Fabric Rendering (v1), Quilt Item Group API, Quilted Fabric Key Bindings (v0), Quilted Fabric Command API (v2), Quilt Client Command API, Quilt Loader, Quilt Block Content Registry API, Quilted Fabric Message API (v1), Quilt DataFixerUpper API, Quilt Surface Rule API, Quilt Resource Loader, Quilted Fabric Transfer API (v1), Quilted Fabric Containers (v0), Quilt Block Extensions API, Quilted Fabric Key Binding API (v1), Quilted Fabric Models (v0), Quilted Fabric Mining Level API (v1), Quilted Fabric Rendering Data Attachment (v1), Quilted Fabric Events Interaction (v0), Quilted Fabric API, Quilted Fabric Particles (v1), Quilted Fabric Dimensions API (v1), Quilted Fabric Renderer API (v1), Better End, Quilted Fabric Content Registries (v0), Quilt Item Extension API, Quilt Command API, Quilt Registry Entry Attachment, Quilted Fabric Item Groups (v0), Quilted Fabric API Lookup API (v1), Quilted Fabric Screen Handler API (v1), Better Nether, Quilt Multipart Entity API, Quilt Item Setting API, Quilt Recipe API, Quilted Fabric Resource Conditions API (v1), Quilted Fabric Textures (v0), Quilted Fabric Data Generation API (v1), Quilted Fabric Item API (v1), Quilt Advancement API, Quilted Fabric Events Lifecycle (v0), Quilt Screen API, Quilt Tooltip API, Quilt Networking, Quilt Block Entity API, Quilt Dimension API, Quilted Fabric Commands (v0), Quilted Fabric Crash Report Info (v1), Quilted Fabric Entity Events (v1), Quilt Crash Info, Quilted Fabric Transitive Access Wideners (v1), Quilted Fabric Client Tags, Quilted Fabric Object Builder API (v1), Quilted Fabric Loot Tables (v1), Quilted Fabric Networking API (v1), Quilted Fabric Registry Sync (v0), Quilted Fabric Rendering (v0), Quilted Fabric Command API (v1), Quilted Fabric Renderer Registries (v1), Quilt Biome API, Quilted Fabric Screen API (v1), Quilted Fabric Convention Tags API (v1), Quilted Fabric API Base, Quilt Lifecycle Events, Quilted Fabric Loot API (v2), Cloth Config v8, BCLib, Quilted Fabric Game Rule API (v1), Quilted Fabric Biome API (v1), Roughly Enough Items, Quilted Fabric Lifecycle Events (v1), Quilted Fabric Networking (v0), Quilt Item Content Registry API, Quilt Registry API, Quilted Fabric BlockRenderLayer Registration (v1), Quilt Tags API), MySplash.zip, Saturn the Donkey's Villagers.zip
[18:41:05] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[18:41:05] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:41:05] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on LEN D32q-20B (NVIDIA High Definition Audio)
[18:41:05] [Render thread/INFO]: Sound engine started
[18:41:05] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/blocks.png-atlas
[18:41:05] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[18:41:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:41:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:41:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:41:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:41:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:41:07] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:41:07] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[18:41:07] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:41:07] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:41:07] [Render thread/ERROR]: Couldn't load tag environmentz:warm_armor as it is missing following references: betternether:cincinnasite_helmet_chestplate (from Better Nether), betternether:cincinnasite_helmet_leggings (from Better Nether), betternether:cincinnasite_helmet_boots (from Better Nether)
[18:41:13] [Render thread/INFO]: [bclib] Loading from builtin Registry
[18:41:13] [Render thread/INFO]: [DataFixerAPI] Ignoring Patch{betternether:5.3.5:21020677}
[18:41:13] [Render thread/INFO]: [bclib] Running Pre Patchers on F:\File\Minecraft\worlds\fabric 1.19.2\saves\Juliet Willow\.
[18:41:13] [Render thread/INFO]: [DataFixerAPI] Everything up to date
[18:41:13] [Render thread/WARN]: Missing data pack Fabric Mods
[18:41:13] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[18:41:14] [Render thread/INFO]: [bclib] Loading from datapack Registry
[18:41:14] [Worker-Main-16/ERROR]: Couldn't load tag environmentz:warm_armor as it is missing following references: betternether:cincinnasite_helmet_chestplate (from Better Nether), betternether:cincinnasite_helmet_leggings (from Better Nether), betternether:cincinnasite_helmet_boots (from Better Nether)
[18:41:14] [Render thread/INFO]: Registered 0 custom recipes.
[18:41:14] [Render thread/INFO]: Modified 0 recipes.
[18:41:14] [Render thread/INFO]: Removed 0 recipes.
[18:41:14] [Render thread/INFO]: Loaded 7 recipes
[18:41:15] [Render thread/INFO]: Loaded 2268 advancements
[18:41:16] [Render thread/INFO]: Applied 22 biome modifications to 22 of 110 new biomes in 60.47 ms
[18:41:16] [Server thread/INFO]: Starting integrated minecraft server version 1.19.2
[18:41:16] [Server thread/INFO]: Generating keypair
[18:41:16] [Server thread/INFO]: [bclib] 
Apply Modifications for minecraft:overworld
    class_1992 (1c13aa46)
        biomes     = 1
        namespaces = minecraft
[18:41:16] [Server thread/INFO]: [bclib] 
Apply Modifications for minecraft:the_end
    class_2169 (7e16e10c)
        biomes     = 21
        namespaces = minecraft, betterend
[18:41:16] [Server thread/INFO]: [bclib] 
Apply Modifications for minecraft:the_nether
    class_4766 (2a7293f9)
        biomes     = 15
        namespaces = minecraft, betternether
[18:41:16] [Server thread/INFO]: [bclib] World Dimensions: 
 - minecraft:overworld: 
     net.minecraft.class_2897@4b30ac1e 
     class_1992 (1c13aa46)
         biomes     = 1
         namespaces = minecraft
 - minecraft:the_end: 
     net.minecraft.class_3754@6f0021de 
     class_2169 (7e16e10c)
         biomes     = 21
         namespaces = minecraft, betterend
 - minecraft:the_nether: 
     net.minecraft.class_3754@66490bfd 
     class_4766 (2a7293f9)
         biomes     = 15
         namespaces = minecraft, betternether
[18:41:16] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:41:18] [Render thread/INFO]: Preparing spawn area: 0%
[18:41:18] [Render thread/INFO]: Preparing spawn area: 0%
[18:41:18] [Render thread/INFO]: Preparing spawn area: 0%
[18:41:18] [Render thread/INFO]: Preparing spawn area: 0%
[18:41:18] [Render thread/INFO]: Preparing spawn area: 25%
[18:41:19] [Render thread/INFO]: Time elapsed: 2438 ms
[18:41:19] [Server thread/INFO]: Changing view distance to 16, from 10
[18:41:19] [Server thread/INFO]: Changing simulation distance to 12, from 0
[18:41:20] [Server thread/INFO]: SaturnoSomaro92[local:E:fb41c83a] logged in with entity id 25 at (25.95701511810402, -59.0, 1.7467920051326955)
[18:41:20] [Server thread/INFO]: SaturnoSomaro92 joined the game
[18:41:20] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [START], registered 6 plugins: DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], REIPlugin [betterend], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[18:41:21] [Render thread/ERROR]: Couldn't load tag environmentz:warm_armor as it is missing following references: betternether:cincinnasite_helmet_chestplate (from Better Nether), betternether:cincinnasite_helmet_leggings (from Better Nether), betternether:cincinnasite_helmet_boots (from Better Nether)
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [START], registered 3 plugins: DefaultClientRuntimePlugin [roughlyenoughitems], REIPlugin [betterend], DefaultClientPlugin [roughlyenoughitems]
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [START], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 6 plugins in 46.41 ms.
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 3 plugins in 104.9 ms.
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 3 plugins in 1.877 ms.
[18:41:21] [Render thread/INFO]: [bclib] Sending hello to server.
[18:41:21] [Server thread/INFO]: [bclib] Received Hello from Client. (server=2.1.1, client=2.1.1)
[18:41:21] [Server thread/INFO]: [bclib] Auto-Sync is disabled for Singleplayer worlds.
[18:41:21] [Render thread/WARN]: [REI] Suppressing Reload Plugins of stage START
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIPlugin] stage [END], registered 6 plugins: DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], REIPlugin [betterend], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIClientPlugin] stage [END], registered 3 plugins: DefaultClientRuntimePlugin [roughlyenoughitems], REIPlugin [betterend], DefaultClientPlugin [roughlyenoughitems]
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIPlugin] with 6 plugins in 28.70 ms.
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIClientPlugin] with 3 plugins in 200.8 ms.
[18:41:21] [REI-ReloadPlugins/INFO]: [REI] Reloaded Plugin Manager [REIServerPlugin] with 3 plugins in 5.200 ms.
[18:41:21] [Render thread/INFO]: Loaded 22 advancements
[18:42:26] [Server thread/INFO]: Saving and pausing game...
[18:42:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:overworld
[18:42:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:the_end
[18:42:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:the_nether
[18:43:35] [Server thread/INFO]: Saving and pausing game...
[18:43:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:overworld
[18:43:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:the_end
[18:43:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:the_nether
[18:43:35] [Server thread/INFO]: SaturnoSomaro92 lost connection: Disconnected
[18:43:35] [Server thread/INFO]: SaturnoSomaro92 left the game
[18:43:35] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:43:36] [Server thread/INFO]: Stopping server
[18:43:36] [Server thread/INFO]: Saving players
[18:43:36] [Server thread/INFO]: Saving worlds
[18:43:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:overworld
[18:43:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:the_end
[18:43:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Juliet Willow]'/minecraft:the_nether
[18:43:37] [Server thread/INFO]: ThreadedAnvilChunkStorage (Juliet Willow): All chunks are saved
[18:43:37] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:43:37] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:43:37] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[18:43:38] [Render thread/INFO]: Stopping!
```

### Other Mods

```shell
better-nether-7.1.1.jar (in order to check the same problem)
RoughlyEnoughItems-9.1.550.jar (for making sure the recipes weren't appearing)
cloth-config-8.2.88-fabric.jar
architectury-6.2.43-fabric.jar
```

**Comment by quiqueck** [comment] 2022-10-13 21:59
duplicate of quiqueck/betternether#71

**Closed as completed by quiqueck** 2022-10-13 21:59 UTC
