### ISSUE TITLE
[Bug] [Suggestion] ¿Could you fix wood textures so they can be compatible with Every Compat?

### ISSUE THREAD

**Issue by Rodas011** [quiqueck/BetterEnd#67] opened 2022-08-24 03:49 UTC
### What happened?

So apparently wood/planks textures from this mod work differently from others and for that, they don't work with Every Compat as they should. **BetterNether works just fine.** My suggestion is just to make wood/planks as they are made in BetterNether, that would be really nice.

All the info bellow:

Words form Every Compat creator, every time BetterEnd error is reported:
"seems like better end might have some weird models for their planks that for some reason dont specify a texture directly in them? Actually they dont even have blockstates and models what the hell"
"aparently this mod dont have any blockstate and block model json at all for those blocks for some reason. I dont really see any reason why a mod that does not have dynamic registration like I do should not have all its resources included in its datapack."
"As for the missing texture it's due to some weirdness in those mods which for some reason do not have models. I might search for a solution or outright disable all of those mod IDs from the wood detection system"

![image](https://user-images.githubusercontent.com/68823524/186319388-962c3314-7c7f-4667-b71b-c0cd5b2a95f2.png)
In the image you can see BetterNether works just fine, (as well as other mods woods).

### BetterEnd

betterend 2.1.0

### BCLib

bclib 2.1.0

### Fabric API

fabric-api-0.58.0+1.19

### Fabric Loader

Fabric Loader 0.14.9

### Minecraft

1.19

### Relevant log output

```shell
[21:32:24] [Render thread/INFO]: Generated runtime CLIENT_RESOURCES for pack Everycomp Generated Pack in: 444 ms
[21:32:24] [Render thread/ERROR]: Could not properly generate Hanging Sign model for Block{supplementaries:betternether/hanging_sign_nether_reed}. Falling back to planks texture : java.io.FileNotFoundException: Could not find any texture associated to the given block betternether:nether_reed_stem
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign loader model for Block{supplementaries:betterend/hanging_sign_end_lotus} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:end_lotus_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign loader model for Block{supplementaries:betterend/hanging_sign_tenanea} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:tenanea_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign loader model for Block{supplementaries:betterend/hanging_sign_helix_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:helix_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign loader model for Block{supplementaries:betterend/hanging_sign_umbrella_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:umbrella_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign loader model for Block{supplementaries:betterend/hanging_sign_jellyshroom} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:jellyshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_mossy_glowshroom} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:mossy_glowshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_pythadendron} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:pythadendron_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_end_lotus} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:end_lotus_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_lacugrove} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lacugrove_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_dragon_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:dragon_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_tenanea} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:tenanea_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_helix_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:helix_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_umbrella_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:umbrella_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_jellyshroom} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:jellyshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign block texture for for Block{supplementaries:betterend/hanging_sign_lucernia} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lucernia_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_mossy_glowshroom} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:mossy_glowshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_pythadendron} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:pythadendron_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_end_lotus} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:end_lotus_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_lacugrove} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lacugrove_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_dragon_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:dragon_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_tenanea} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:tenanea_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_helix_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:helix_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_umbrella_tree} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:umbrella_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_jellyshroom} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:jellyshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Hanging Sign item texture for for Block{supplementaries:betterend/hanging_sign_lucernia} : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lucernia_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_pythadendron : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:pythadendron_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_dragon_tree : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:dragon_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_mossy_glowshroom : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:mossy_glowshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_jellyshroom : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:jellyshroom_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_helix_tree : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:helix_tree_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_tenanea : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:tenanea_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_lucernia : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lucernia_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_end_lotus : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:end_lotus_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_lacugrove : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lacugrove_planks
[21:32:24] [Render thread/ERROR]: Failed to generate Sign Post item texture for for betterend/sign_post_umbrella_tree : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:umbrella_tree_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_pythadendron : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:pythadendron_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_dragon_tree : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:dragon_tree_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_mossy_glowshroom : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:mossy_glowshroom_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_jellyshroom : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:jellyshroom_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_helix_tree : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:helix_tree_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_tenanea : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:tenanea_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_lucernia : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lucernia_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_end_lotus : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:end_lotus_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_lacugrove : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:lacugrove_planks
[21:32:25] [Render thread/ERROR]: Failed to generate Sign Post block texture for for betterend/sign_post_umbrella_tree : java.io.FileNotFoundException: Could not find any texture associated to the given block betterend:umbrella_tree_planks
[21:32:25] [Render thread/INFO]: Generated runtime CLIENT_RESOURCES for pack Supplementaries Generated Pack in: 464 ms
```

### Other Mods

```shell
[21:31:47] [main/INFO]: Loading 125 mods:
	- architects_palette 2.1.1
	- architectury 5.12.42
	- bclib 2.1.0
	- betterend 2.1.0
	- betternether 7.1.0
	- biomemakeover 1.19-1.5.9
	- cardinal-components-base 5.0.1 via polymorph
	- cardinal-components-block 5.0.1 via polymorph
	- cardinal-components-entity 5.0.1 via polymorph
	- cardinal-components-item 5.0.1 via polymorph
	- cem 0.7.1
	- charm 4.2.2
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.73 via ecologics
	- coat 1.0.0-beta.17+mc22w17a via completeconfig
	- colormatic 3.1.2+mc.1.19
	- com_electronwill_night-config_core 3.6.2 via charm
	- com_electronwill_night-config_toml 3.6.2 via charm
	- com_github_llamalad7_mixinextras 0.0.11 via debugify
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- completeconfig 2.0.0
	- completeconfig-base 2.0.0 via completeconfig
	- completeconfig-gui-cloth 2.0.0 via completeconfig
	- completeconfig-gui-coat 2.0.0 via completeconfig
	- continuity 2.0.1+1.19
	- cullleaves 2.3.4
	- debugify 2.3.2
	- dynamicfps 2.2.0
	- ecologics 2.1.8.1
	- entity_texture_features 4.0.2
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- everycomp 1.19.1-2.0.2
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.10+5187d39fa9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.9
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- frame 0.26.1+1.19-fabric
	- frame-api-base 0.2.1+906ebc04a9 via frame
	- frame-blocks-v0 0.1.3+233e7428a9 via frame
	- frame-config-v0 0.3.1+0fa45150a9 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-enchantments-v0 0.1.0+4093105da9 via frame
	- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
	- frame-items-v0 0.1.3+906ebc04a9 via frame
	- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
	- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
	- frame-rendering-v0 0.1.5+906ebc04a9 via frame
	- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
	- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
	- frame-woods-v0 0.2.1+6a33fbada9 via frame
	- indium 1.0.7+mc1.19
	- iris 1.2.6
	- jade 7.7.1
	- java 17
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- memoryleakfix 1.19-0.7.0
	- midnightlib 0.5.2 via cullleaves
	- minecraft 1.19
	- mm 2.3 via frame-enchantments-v0
	- modmenu 4.0.4
	- moonlight 1.19-2.0.15
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.4 via sodium
	- patchouli 1.19-74-FABRIC
	- polymorph 0.45.0+1.19.2
	- pride 1.1.2+1.19 via lambdynlights
	- roughlyenoughitems 9.1.530
	- sodium 0.4.2+build.16
	- spruceui 4.0.0+1.19 via lambdynlights
	- supplementaries 1.19-2.0.13
	- terralith 2.3
	- transparent 5.1.0
	- twigs 2.0.0-beta.9+1.19-fabric
	- xaerominimapfair 22.12.0
	- xaeroworldmap 1.26.1
```

**Comment by aesopcmc** [comment] 2022-09-03 05:41
i got this error too

**Comment by quiqueck** [comment] 2022-10-08 18:59
BetterEnd is adding those Models/Texture at runtime in Code, which appears to be the cause of this issue. I'll have to talk to the Every Compat dev's to find a solution here.

**Comment by quiqueck** [comment] 2022-10-08 19:00
duplicate of #71

**Closed as completed by quiqueck** 2022-10-08 19:00 UTC
Labels: ⚡ compatibility
