### ISSUE TITLE
Can't create thallasium forged plate[Bug] 

### ISSUE THREAD

**Issue by Elemental2021** [quiqueck/BetterEnd#65] opened 2022-08-19 13:40 UTC
### What happened?

I put thallasium ingots in a thallasium anvil and then I put in a thallasium hammer but it did not let me craft any thing this was in Minecraft 1.19.2 it would not work on a server or on a single player world

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Other Mods

```shell
apple skin, architectury api, boosted brightness, citresewn, Clumps, continuity, dynamic fps, fabric language kotlin, ferritecore, indium, inventoryhud+, iris shaders, lazydfu, lithium, mod menu, perspective mod redux, reese's sodium options, replay mod, REI, shulker box tool tips, sodium extra, sodium, zoomify.
```

**Comment by Elemental2021** [comment] 2022-08-21 11:07
I tried to craft it with out the mods and it still did not work

**Comment by quiqueck** [comment] 2022-10-08 18:31
Duplicate of #64

**Closed as completed by quiqueck** 2022-10-08 18:31 UTC
