### ISSUE TITLE
[Bug] 1.19.3 Some outer island biomes are causing crashes (I think)

### ISSUE THREAD

**Issue by Greshtahu** [quiqueck/BetterEnd#201] opened 2023-04-22 04:43 UTC
### What happened?

For reference, this is a previous 1.19.1 Terralith/Incindium origins modded world that used to have the Nullscape datapack installed before I deleted any trace of it and trimmed the end chunks until it was just the main island.

I have also added more mods which will be listed later. 

MAIN ISSUE:
Whenever I venture out to the outer islands, the BetterEnd terrain loads normally but eventually my server shuts down and restarts when I go to certain areas. 

Whenever the server comes back up and I log back into that area, it shuts the server down right after. I have to quickly teleport myself back to spawn in the second after I press log in before the server shuts down again.

This issue does not happen on the offline copy of the world I have so I can't tell what is causing it.

the main description is always "Exception in server tick loop"

WHAT I'VE TRIED
I have already deleted the following from the server files and let the world reload them:
banned-ips.json
banned-players.json
ops.json
usercache.json
whitelist.json

I have tried just making copies then just deleting the DIM1 folder but when the end loads, I still get the same issue and the main island does not spawn with a exit portal to get out or to summon the dragon, nor does the dragon spawn (If I use my old end island, I can resummon the dragon which makes the BetterEnd exit portal spawn on top. I thought this was interesting).

I have checked the biome source files for the level.dat file and it shows the seed 1373446487885267781 and the type as bclib:end_biome_source

I have updated all the mods to their most recent version as far as I can tell.

I saw prev posts about certain biomes causing it but I can never tell which one it is because the game loads them before I see which ones.

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.76.1

### Fabric Loader

0.14.19

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2023-04-22 03:25:21
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 4.9.184-xxxx-std-ipv6-64
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2385936296 bytes (2275 MiB) / 3397386240 bytes (3240 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 1
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 85945.92
	Virtual memory used (MB): 58023.66
	Swap memory total (MB): 21501.99
	Swap memory used (MB): 2305.31
	JVM Flags: 4 total; -Xmx6144M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	Fabric Mods: 
		ae2: Applied Energistics 2 13.0.6-beta
		architectury: Architectury 7.1.78
		archon: Archon 0.5.1
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			omega-config: OmegaConfig 1.3.0+1.19.2
		bclib: BCLib 2.2.4
		betterend: Better End 3.1.2
		betterfortresses: YUNG's Better Nether Fortresses 1.19.3-Fabric-1.1.1
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.3-Fabric-3.3.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.3-Fabric-2.2.0
		betterstrongholds: YUNG's Better Strongholds 1.19.3-Fabric-3.3.0
		chunky: Chunky 1.3.53
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		dimdoors: DimensionalDoors 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.1.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		explorify-fabric: Explorify 1.19-1.3.0
		extraorigins: Extra Origins 1.19-4
		fabric-api: Fabric API 0.76.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.23+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.2+2961b4a085
			fabric-commands-v0: Fabric Commands (v0) 0.2.40+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.3+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.3+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.14+b5470ac785
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.22+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.26+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.33+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.3+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+b93ffe4d85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.19
		geckolib: Geckolib 4.0.6
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 2.6.1
		incendium: Incendium 5.1.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 12.4.0.22
		journeymap: Journeymap 5.9.5
			journeymap-api-fabric: JourneyMap API 1.19.3-1.9-fabric-SNAPSHOT
		lithium: Lithium 0.11.1
		lootr: Lootr 0.4.25.65
		mcpitanlibarch: MCPitanLib 1.6.3-1.19.3-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		midnightlib: MidnightLib 1.1.0
		minecraft: Minecraft 1.19.3
		origins: Origins 1.8.1
			apoli: Apoli 2.7.1
				additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
				calio: Calio 1.8.0
				playerabilitylib: Pal 1.7.0
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		origins-classes: Origins: Classes 1.5.0
		patchouli: Patchouli 1.19.3-78-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.3+1.14.4-1.20
			kanos_config: Kanos Config 0.4.0+1.14.4-1.19.4
		philipsruins: Philip`s ruins 1.19.3
		phosphor: Phosphor 0.8.1
		pipeplus: PipePlus 1.19.4-0.5.2
		quarryplus: QuarryPlus 19.3.740
		reborncore: Reborn Core 5.5.0
			team_reborn_energy: Energy 2.3.0
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.9.2
			libblockattributes: LibBlockAttributes 0.12.0
				libblockattributes_core: LibBlockAttributes (Core) 0.12.0
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.12.0
				libblockattributes_items: LibBlockAttributes (Items) 0.12.0
			libmultipart: LibMultiPart 0.9.2
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.9.2
			libnetworkstack: Lib Network Stack 0.8.0
			simple_pipes: SimplePipeTest 0.9.2
		t_and_t: Towns and Towers 1.10.1
			blue_endless_jankson: jankson 1.2.1
		techreborn: Tech Reborn 5.5.0
		terralith: Terralith 2.3
		yigd: You're in Grave Danger 1.5.1
		yungsapi: YUNG's API 1.19.3-Fabric-3.9.0
			org_javassist_javassist: javassist 3.28.0-GA
		yungsextras: YUNG's Extras 1.19.3-Fabric-3.2.0
	Server Running: true
	Player Count: 0 / 40; []
	Data Packs: vanilla, dimdoors:classic, dimdoors:default, fabric, file/New-Ocean-Ruins.zip (incompatible), file/anti enderman grief v1.1.3.zip (incompatible), file/anti ghast grief v1.1.3.zip (incompatible), file/cauldron concrete v2.0.6.zip (incompatible), file/durability ping v1.1.3.zip (incompatible), file/more mob heads v2.11.1.zip (incompatible), file/multiplayer sleep v2.6.3.zip (incompatible), file/name colors v1.0.1.zip (incompatible), file/nether portal coords v1.1.3.zip (incompatible), file/player head drops v1.1.3.zip (incompatible), file/spawning spheres v1.1.3.zip (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
Archon
Additional Enchanted Miner
Applied Energistics 2
Architectury API (Fabric/Forge)
Bobby
Chunky
Cloth Config API (Fabric/Forge)
DimensionalDoors
Explorify – Dungeons & Structures
Extra Origins
Fabric API
Fabric Language Scala
GeckoLib
Incendium
Indium
JourneyMap
Just Enough Items (JEI)
Lootr (Fabric)
Lithium
MCPitanLib (Fabric/Forge)
MidnightLib
Mod Menu
Mouse Tweaks
Origins (Fabric)
Origins: Classes
Patchouli (Fabric/Quilt)
Pehkui
Philip's Ruins
Phosphor (Fabric)
PipePlus (Fabric)
Reborn Core
Simple BC Pipes
Sodium
Tech Reborn
Terralith
The Graveyard (FABRIC)
Towns and Towers
You're in Grave Danger
YUNG's API (Fabric)
YUNG's Better Mineshafts (Fabric)
YUNG's Better Nether Fortresses (Fabric)
YUNG's Better Ocean Monuments (Fabric)
YUNG's Better Strongholds (Fabric)
YUNG's Extras (Fabric)
```

**Comment by quiqueck** [comment] 2023-05-16 11:11
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:11 UTC
