### ISSUE TITLE
Anvil recipes not working again witn modpack BetterMC

### ISSUE THREAD

**Issue by vtzay** [quiqueck/BetterEnd#93] opened 2022-10-11 21:19 UTC
### What happened?

I found similar bug with https://github.com/paulevsGitch/BetterEnd/issues/429.

All anvil recipes witn end material not working. I play on server with modpack BetterMC.
![image](https://user-images.githubusercontent.com/106840997/195199482-b1798f78-cd01-49b3-855c-10bd93c45382.png)
This recipe not working on any anvil and with any hammer and with any item order (hammer + shard and shard + hammer)
I think this a conflict with a other mod, because after open and close REI settings anvil GUI was changes (arrow buttons was added to GUI)
![image](https://user-images.githubusercontent.com/106840997/195199811-a20bb05e-1ce5-4c43-b30f-fe6be6f4c37e.png)
Also REI do not show any anvil recipes, e.g. a clicked LMB to "forged plate" and nothing happens, if i clicked RMB REI open recipes from forged plates.
![image](https://user-images.githubusercontent.com/106840997/195200315-259bbdaf-853b-4ad0-9943-2e055d95ea7b.png)

### BetterEnd

2.1.0

### BCLib

2.1.0

### Minecraft

1.19.2

### Other Mods

```shell
Modpack BetterMC
```

**Comment by quiqueck** [comment] 2022-10-11 21:34
Duplicate of #64

**Closed as completed by quiqueck** 2022-10-11 21:34 UTC
