### ISSUE TITLE
[Bug] Infusion pedestal crashes server

### ISSUE THREAD

**Issue by ColdStoneSys** [quiqueck/BetterEnd#194] opened 2023-04-04 00:11 UTC
### What happened?

As soon as i placed an end crystal on an infusion pedestal to make an eternal crystal the server crashed and I can't log back in.

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.74.0

### Fabric Loader

0.14.18

### Minecraft

1.19.3

### Relevant log output

```shell
Description: Ticking block entity
......
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:particle_type / betterend:glowing_sphere])
......
-- Block entity being ticked --
Details:
	Name: betterend:infusion_pedestal // org.betterx.betterend.blocks.entities.InfusionPedestalEntity
	Block: Block{betterend:infusion_pedestal}[has_item=true,has_light=false,state=default]
	Block location: World: (707,70,743), Section: (at 3,6,7 in 44,4,46; chunk contains blocks 704,-64,736 to 719,319,751), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,-64,512 to 1023,319,1023)
	Block: Block{betterend:infusion_pedestal}[has_item=true,has_light=false,state=default]
	Block location: World: (707,70,743), Section: (at 3,6,7 in 44,4,46; chunk contains blocks 704,-64,736 to 719,319,751), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,-64,512 to 1023,319,1023)
```

### Other Mods

```shell
Fabric Mods: 
		additionalstructures: Additional Structures 4.1.1
		advanced_reborn: Advanced Reborn 1.1.5
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		ae2: Applied Energistics 2 13.0.6-beta
		architectury: Architectury 7.1.70
		attributefix: AttributeFix 18.0.1
		balm-fabric: Balm 5.0.4
		bclib: BCLib 2.2.4
		betterend: Better End 3.1.2
		betternether: Better Nether 8.1.3
		bigpony: Big Pony 1.8.0
			kirin: Kirin UI 1.13.2
		cardinal-components: Cardinal Components API 5.1.0
                chisel: Chisel Refabricated 1.4.5
		chunky: Chunky 1.3.53
		cloth-config: Cloth Config v9 9.0.94
                clumps: Clumps 9.0.0+16
		collective: Collective 6.48
		comforts: Comforts 6.1.1+1.19.3
                computercraft: CC: Restitched 1.102.0
                connectivity: Connectivity Mod 1.19.3-3.9
		convenient-mobgriefing: Convenient mobGriefing 2.1.0
		creativecore: CreativeCore (Fabric) 2.10.4
                croptopia: Croptopia 2.2.2
                ctov: ChoiceTheorem's Overhauled Villages 3.1.8
		ecologics: Ecologics 2.1.12
                friendsandfoes: Friends&Foes 1.7.5
                imst: Immersive structures 2.0.7
		incendium: Incendium 5.1.4
		inventorysorter: Inventory Sorter 1.8.10-1.19.3
                ironchests: Iron Chests 1.7.8
                jei: Just Enough Items 12.2.0.16
		journeymap: Journeymap 5.9.3
                ledger: Ledger 1.2.6
                mcpitanlibarch: MCPitanLib 1.4.3-1.19.3-fabric
		minecraft: Minecraft 1.19.3
		mvs: Vanilla Structure Mod 2.5.12-1.19.3
		naturescompass: Nature's Compass 1.19.3-2.1.1-fabric
		nochatreports: No Chat Reports 1.19.3-v2.0.0
		patchouli: Patchouli 1.19.3-78-FABRIC
		pfm: Paladin's Furniture 1.1.2
		reborncore: Reborn Core 5.5.0
		serversleep_mr: ServerSleep 1-datapack
		styled-nicknames: Styled Nicknames 1.2.0+1.19.3
		tabtps-fabric: TabTPS 1.3.16
                techreborn: Tech Reborn 5.5.0
		terralith: Terralith 2.3.7b
		textile_backup: Textile Backup 2.5.0-1.19
                travelersbackpack: Traveler's Backpack 1.19.3-8.3.2
                treeharvester: Tree Harvester 7.2
		vanillatweaks: VanillaTweaks 1.5.64
		waystones: Waystones 12.2.0
```

**Comment by Greshtahu** [comment] 2023-05-12 03:36
I am getting the same issue with this. Granted I did one of the crystal shards last instead of the end crystal but got the same result.

**Comment by quiqueck** [comment] 2023-05-16 11:09
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:09 UTC
