### ISSUE TITLE
All Anvil Crafting Recipes are broken [Bug] 

### ISSUE THREAD

**Issue by diamonddevv** [quiqueck/BetterEnd#66] opened 2022-08-22 16:10 UTC
### What happened?

Every single anvil crafted recipe is impossible.

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Other Mods

```shell
Apple Skin
Bad Packets
Better Nether
DiaLabs
EMI
Enderism
Fabric API
Ferrite Core
Lambdynamiclights
lazydfu
lithium
modmenu
Mouse Tweaks
Sharp Tone
Sodium
Starlight
WTHIT
```

**Comment by ghost** [comment] 2022-08-23 18:11
I can confirm this issue for the same version, without additional mods.

**Comment by quiqueck** [comment] 2022-10-08 18:31
Duplicate of #64

**Closed as completed by quiqueck** 2022-10-08 18:31 UTC
