### ISSUE TITLE
BetterEnd crashes when we go to the end islands / cities

### ISSUE THREAD

**Issue by ratcaged** [quiqueck/BetterEnd#162] opened 2023-02-21 00:15 UTC
We go through the portal to get to the biomes/cities/islands and it crashes. For the crash log provided, it seems to be caused by rendering specific particles but I don't know how to fix that.

[crash-2023-02-20_23.44.38-server.txt](https://github.com/quiqueck/BetterEnd/files/10788484/crash-2023-02-20_23.44.38-server.txt)

edit: idk if this changes anything but the server world is a copy of a singleplayer world, the singleplayer world has all the same mods and it doesnt crash

**Comment by BrickOyster** [comment] 2023-02-23 20:50
same problem on Fabric
trying to figure out whats the exact reason 
Was traveling from x 0 z barely changed and ended up at x=-2305.97, y=103.69, z=-321.36
tell me what to send so you can see where I was close too (structure/biome)
The error message refers to src/main/java/org/betterx/betterend/blocks/AncientEmeraldIceBlock.java to the method makeParticles of AncientEmeraldIceBlock.java class with a null pointer exception
[crash-2023-02-23_22.44.23-server.txt](https://github.com/quiqueck/BetterEnd/files/10818336/crash-2023-02-23_22.44.23-server.txt)
refrence to method for whoever wants to see here
![image](https://user-images.githubusercontent.com/60844423/221027067-f94c9af3-81c1-4920-b1f3-58d3dd1a5397.png)

Ok edit:
I just replicated the crash in the overworld
I made a 2x2x1 anciendemeraldice pool and put 1 source block on it and it crashed with same error
![image](https://user-images.githubusercontent.com/60844423/221029390-41c4c41f-f467-4222-9f50-53418f54f3f2.png)

tried same think in singleplayer
didnt crash and I see the culprit I think freezing water making snow particles
![image](https://user-images.githubusercontent.com/60844423/221030494-b8318a19-75b0-44cd-bc7d-9c46c27ba76c.png)

server again
![image](https://user-images.githubusercontent.com/60844423/221031087-257be2ca-fe62-427f-aee6-0cb54f5ade1e.png)

after crash joined to this
![image](https://user-images.githubusercontent.com/60844423/221031377-b42e3cb8-56fa-494d-a6f4-23d2c6833041.png)
frozen water next to the emeraldice

and crashed shortly after

Hope this helps the developers

**Comment by quiqueck** [comment] 2023-05-16 11:10
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:10 UTC
