### ISSUE TITLE
[Suggestion] Textures License

### ISSUE THREAD

**Issue by JurajVajda** [quiqueck/BetterEnd#142] opened 2023-02-03 19:15 UTC
### Description

While the license says that the mod is MIT, the textures don't fall under the same license. It would be helpful to have list of textures and their licenses included in LICENSE file (or somewhere in the repo) so its clear what textures are included under public domain and what textures are restricted or non-reusable.

**Comment by quiqueck** [comment] 2023-02-12 13:04
Duplicate of quiqueck/BetterNether#110

**Closed as completed by quiqueck** 2023-02-12 13:04 UTC
Labels: 🥈 duplicate

**Comment by JurajVajda** [comment] 2023-02-13 16:23
@quiqueck this is not duplicate since the ask is to update the license info in this repository, the issue in BetterNether repository is in that repository context
