### ISSUE TITLE
[Bug] all crystalite armor  only gives stats if they're on the body, which they can't be on

### ISSUE THREAD

**Issue by playr-lol** [quiqueck/BetterEnd#483] opened 2024-09-29 16:31 UTC
### What happened?

the title, crystalite leggings should give armor and toughness for when they're on legs, but it's only for the body

### BetterEnd

 21.0.11 (1.21)

### BCLib

21.0.13

### Fabric API

0.102.0

### Fabric Loader

0.16.5

### Minecraft

1.20.4

**Comment by playr-lol** [comment] 2024-10-01 22:22
actually, most attributes for most armors are broken (armored elytra, knockback resistance in main hand, terminite leggins, no protection? thallasium, no protection w/ attack damage in main hand)

**Comment by OpenBagTwo** [comment] 2024-10-14 19:42
This is a dupe of #446. Please close. Note that there's a build you can test that has a fix for this issue [here.](https://github.com/OpenBagTwo/BetterEnd/releases/tag/21.0.12%2Bopenbagtwo.241014)

**Closed as completed** 2024-10-20 00:11 UTC
