### ISSUE TITLE
[Bug] Server crashing due to particle generation from a block

### ISSUE THREAD

**Issue by LeonardoPalinkas** [quiqueck/BetterEnd#198] opened 2023-04-18 18:49 UTC
### What happened?

Hello, I've been having a problem with the generation of my End. We are on a server and whenever there is a player loading the chunks it crashes. The crash-reports reports that the problem is in the particles generated by a block.

What can I do?

Crash-report:

[crash-2023-04-18_15.41.28-server.txt](https://github.com/quiqueck/BetterEnd/files/11265267/crash-2023-04-18_15.41.28-server.txt)

### BetterEnd

3.1.3

### BCLib

2.2.4

### Fabric API

0.14.19

### Minecraft

1.19.3

**Comment by LeonardoPalinkas** [comment] 2023-04-18 18:52
here are all the mods installed on the server:

![imagem_2023-04-18_155150939](https://user-images.githubusercontent.com/49947971/232876051-e2a47df7-0087-42c0-98bc-eec200847eeb.png)
![imagem_2023-04-18_155205578](https://user-images.githubusercontent.com/49947971/232876213-3539b2ce-8806-4140-a844-f800ef15a354.png)
![imagem_2023-04-18_155210840](https://user-images.githubusercontent.com/49947971/232876266-6bfdf6f5-f4d5-44e2-890a-514e06c0fbff.png)

**Comment by Javano** [comment] 2023-04-29 20:19
+1 experiencing the same error.

[crash-2023-04-29_13.12.39-server.txt](https://github.com/quiqueck/BetterEnd/files/11360017/crash-2023-04-29_13.12.39-server.txt)

**Comment by quiqueck** [comment] 2023-05-16 11:05
Duplicate of #205

**Closed as completed** 2023-05-16 11:09 UTC
