### ISSUE TITLE
[Bug] [1.19.2] Crash when entering the End

### ISSUE THREAD

**Issue by lartts** [quiqueck/BetterEnd#188] opened 2023-03-24 11:16 UTC
### What happened?

When entering the End, Minecraft suddenly crashes, this crash is implied to have happened because of "Feature order cycle found". Here is the crash log: https://pastebin.pl/view/8a06b58f

Below I included the crash report

### BetterEnd

2.1.4

### BCLib

2.1.6

### Fabric API

QFAPI 6.0.0-beta.2

### Fabric Loader

Quilt Loader 0.18.3

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2023-03-24 17:02:11
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / betterend:chorus_forest]=net.minecraft.class_1959@4acfc361}, Reference{ResourceKey[minecraft:worldgen/biome / betterend:old_bulbis_gardens]=net.minecraft.class_1959@7a69866d}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at org.betterx.bclib.api.v2.generator.BCLChunkGenerator.lambda$rebuildFeaturesPerStep$5(BCLChunkGenerator.java:103)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
Mixins in Stacktrace: None found

-- Chunk to be generated --
Details:
	Location: 5,-2
	Position hash: -8589934587
	Generator: BCLib - Chunk Generator (3bf3e773)
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:679)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Mixins in Stacktrace:
	net.minecraft.class_3898:
		org.quiltmc.qsl.entity.multipart.mixin.ThreadedAnvilChunkStorageMixin (#quilt_entity_multipart:quilt_entity_multipart.mixins.json)
		org.quiltmc.qsl.networking.mixin.accessor.ThreadedAnvilChunkStorageAccessor (#quilt_networking:quilt_networking.mixins.json)
		dev.architectury.mixin.fabric.MixinChunkMap (#architectury:architectury.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ThreadedAnvilChunkStorageMixin (#quilted_fabric_lifecycle_events_v1:quilted_fabric_lifecycle_events_v1.mixins.json)

-- Block being collided with --
Details:
	Block: Block{minecraft:end_portal}
	Block location: World: (10,66,635), Section: (at 10,2,11 in 0,4,39; chunk contains blocks 0,-64,624 to 15,319,639), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
Stacktrace:
	at net.minecraft.class_1297.method_5852(class_1297.java:1063)
	at net.minecraft.class_1297.method_36974(class_1297.java:783)
	at net.minecraft.class_1297.method_5784(class_1297.java:752)
	at net.minecraft.class_1309.method_26318(class_1309.java:2282)
	at net.minecraft.class_1309.method_6091(class_1309.java:2227)
	at net.minecraft.class_1657.method_6091(class_1657.java:1638)
	at net.minecraft.class_1309.method_6007(class_1309.java:2680)
	at net.minecraft.class_1657.method_6007(class_1657.java:570)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Mixins in Stacktrace:
	net.minecraft.class_1297:
		com.acikek.voidcrafting.mixin.EntityMixin (#voidcrafting:voidcrafting.mixins.json)
		eu.ha3.presencefootsteps.mixins.IEntity (#presencefootsteps:presencefootsteps.mixin.json)
		com.yungnickyoung.minecraft.travelerstitles.mixin.EntityChangeDimensionMixin (#travelerstitles:travelerstitles.mixins.json)
		net.kyrptonaught.customportalapi.mixin.EntityMixin (#customportalapi:customportalapi.mixins.json)
		com.github.Soulphur0.mixin.entity.EntityMixin (#comet:comet.mixins.json)
		nordmods.uselessreptile.common.mixin.SetThirdPersonEntityMixin (#uselessreptile:uselessreptile.mixins.json)
		org.quiltmc.qsl.worldgen.dimension.mixin.EntityMixin (#quilt_dimension:quilt_dimension.mixins.json)
		corgitaco.corgilib.mixin.MixinEntity (#corgilib:corgilib.mixins.json)
		org.quiltmc.qsl.crash.mixin.EntityMixin (#quilt_crash_info:quilt_crash_info.mixins.json)
		dev.tr7zw.entityculling.mixin.CullableMixin (#entityculling:entityculling.mixins.json)
		org.quiltmc.qsl.entity_events.mixin.EntityMixin (#quilt_entity_events:quilt_entity_events.mixins.json)
		com.sonicether.soundphysics.mixin.EntityMixin (#sound_physics_remastered:sound_physics_remastered.mixins.json)
		org.betterx.betterend.mixin.common.EntityMixin (#betterend:betterend.mixins.common.json)
		dev.architectury.mixin.fabric.MixinEntity (#architectury:architectury.mixins.json)
	net.minecraft.class_1309:
		org.quiltmc.qsl.entity_events.mixin.LivingEntityMixin (#quilt_entity_events:quilt_entity_events.mixins.json)
		net.fabricmc.fabric.mixin.entity.event.elytra.LivingEntityMixin (#quilted_fabric_entity_events_v1:quilted_fabric_entity_events_v1.mixins.json)
		ladysnake.illuminations.mixin.LivingEntityMixin (#illuminations:illuminations.mixins.json)
		tfar.hitmarker.mixin.LivingEntityMixin (#hitmarker:hitmarker.mixins.json)
		net.sydokiddo.auditory.mixin.items.WeaponSwingMixin (#auditory:auditory.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.LivingEntityMixin (#quilted_fabric_lifecycle_events_v1:quilted_fabric_lifecycle_events_v1.mixins.json)
		eu.ha3.presencefootsteps.mixins.ILivingEntity (#presencefootsteps:presencefootsteps.mixin.json)
		dev.architectury.mixin.fabric.LivingDeathInvoker (#architectury:architectury.mixins.json)
		org.quiltmc.qsl.item.setting.mixin.LivingEntityMixin (#quilt_item_setting:quilt_item_setting.mixins.json)
		org.betterx.bclib.mixin.common.elytra.LivingEntityMixin (#bclib:bclib.mixins.common.json)
		net.bettercombat.mixin.LivingEntityAccessor (#bettercombat:bettercombat.mixins.json)
		net.diamonddev.enderism.mixin.LivingEntityMixin (#enderism:enderism.mixins.json)
		org.orecruncher.dsurround.mixins.core.MixinLivingEntity (#dsurround:dsurround.mixins.json)
		com.acikek.purpeille.mixin.LivingEntityMixin (#purpeille:purpeille.mixins.json)
		net.fabricmc.fabric.mixin.entity.event.quilt.LivingEntityAccessor (#quilted_fabric_entity_events_v1:quilted_fabric_entity_events_v1.mixins.json)
		net.fabricmc.fabric.mixin.entity.event.LivingEntityMixin (#quilted_fabric_entity_events_v1:quilted_fabric_entity_events_v1.mixins.json)
		dev.architectury.mixin.fabric.MixinLivingEntity (#architectury:architectury.mixins.json)
		net.dragonloot.mixin.LivingEntityMixin (#dragonloot:dragonloot.mixins.json)
		net.enderitemc.enderitemod.mixin.MobEntityMixin (#enderitemod:enderitemod.mixins.json)
		visuality.mixin.LivingEntityMixin (#visuality:visuality.mixins.json)
		com.natamus.collective.fabric.mixin.LivingEntityMixin (#collective:collective-fabric.mixins.json)
		net.bettercombat.mixin.LivingEntityMixin (#bettercombat:bettercombat.mixins.json)
		org.quiltmc.qsl.entity_events.mixin.LivingEntityDeathEventMixin (#quilt_entity_events:quilt_entity_events.mixins.json)
		net.bunten.enderscape.mixin.LivingEntityMixin (#enderscape:enderscape.mixins.json)
		org.betterx.betterend.mixin.common.LivingEntityMixin (#betterend:betterend.mixins.common.json)
		org.quiltmc.qsl.entity.effect.mixin.LivingEntityMixin (#quilt_status_effect:quilt_status_effect.mixins.json)
		nordmods.uselessreptile.common.mixin.SetFirstPersonLivingEntityMixin (#uselessreptile:uselessreptile.mixins.json)
		eu.ha3.presencefootsteps.mixins.MLivingEntity (#presencefootsteps:presencefootsteps.mixin.json)
		com.github.Soulphur0.mixin.entity.LivingEntityMixin (#comet:comet.mixins.json)
	net.minecraft.class_1657:
		dev.kosmx.playerAnim.mixin.PlayerEntityMixin (#player-animator:playerAnimator-common.mixins.json)
		ladysnake.illuminations.mixin.PlayerEntityMixin (#illuminations:illuminations.mixins.json)
		net.enderitemc.enderitemod.mixin.EnderiteRespawnAnchorMixin (#enderitemod:enderitemod.mixins.json)
		de.kxmischesdomi.just_end_anchor.mixin.PlayerEntityMixin (#just_end_anchor:just_end_anchor.mixins.json)
		net.bunten.enderscape.mixin.PlayerMixin (#enderscape:enderscape.mixins.json)
		net.bettercombat.mixin.PlayerEntityAccessor (#bettercombat:bettercombat.mixins.json)
		net.bettercombat.mixin.PlayerEntityMixin (#bettercombat:bettercombat.mixins.json)
		com.acikek.purpeille.mixin.PlayerEntityMixin (#purpeille:purpeille.mixins.json)
		dev.architectury.mixin.fabric.LivingDeathInvoker (#architectury:architectury.mixins.json)
		net.sydokiddo.auditory.mixin.items.ItemDropSoundMixin (#auditory:auditory.mixins.json)
		potionstudios.byg.mixin.common.entity.MixinPlayer (#byg:byg.mixins.json)
		org.betterx.betterend.mixin.common.PlayerMixin (#betterend:betterend.mixins.common.json)
		com.natamus.collective.fabric.mixin.PlayerMixin (#collective:collective-fabric.mixins.json)
		net.enderitemc.enderitemod.mixin.EnderiteShieldPlayerEntityMixin (#enderitemod:enderitemod.mixins.json)
		net.fabricmc.fabric.mixin.entity.event.elytra.PlayerEntityMixin (#quilted_fabric_entity_events_v1:quilted_fabric_entity_events_v1.mixins.json)
		net.fabricmc.fabric.mixin.entity.event.PlayerEntityMixin (#quilted_fabric_entity_events_v1:quilted_fabric_entity_events_v1.mixins.json)
		dev.architectury.mixin.fabric.PlayerAttackInvoker (#architectury:architectury.mixins.json)
		org.quiltmc.qsl.datafixerupper.mixin.PlayerEntityMixin (#quilt_datafixerupper:quilt_datafixerupper.mixins.json)
		dev.architectury.mixin.fabric.MixinPlayer (#architectury:architectury.mixins.json)
		com.dragonfight.mixin.dragon.PlayerTickMixin (#dragonfight:dragonfight.mixins.json)
		net.combatroll.mixin.PlayerEntityMixin (#combatroll:combatroll.mixins.json)
		com.github.Soulphur0.mixin.entity.player.PlayerEntityMixin (#comet:comet.mixins.json)
		dev.stashy.extrasounds.mixin.inventory.InventoryDropSound (#extrasounds:extrasounds.mixins.json)
		com.teamremastered.endrem.mixin.accessor.PlayerEntityAccessorMixin (#endrem:endrem.mixins.json)
		org.quiltmc.qsl.entity.multipart.mixin.PlayerEntityMixin (#quilt_entity_multipart:quilt_entity_multipart.mixins.json)
		net.combatroll.mixin.PlayerEntityAccessor (#combatroll:combatroll.mixins.json)
		net.dragonloot.mixin.PlayerEntityMixin (#dragonloot:dragonloot.mixins.json)
	net.minecraft.class_3222:
		net.fabricmc.fabric.mixin.event.interaction.ServerPlayerEntityMixin (#quilted_fabric_events_interaction_v0:quilted_fabric_events_interaction_v0.mixins.json)
		org.quiltmc.qsl.entity_events.mixin.LivingEntityDeathEventMixin (#quilt_entity_events:quilt_entity_events.mixins.json)
		org.betterx.betterend.mixin.common.ServerPlayerMixin (#betterend:betterend.mixins.common.json)
		net.fabricmc.fabric.mixin.container.ServerPlayerEntityMixin (#quilted_fabric_containers_v0:quilted_fabric_containers_v0.accurate.mixins.json)
		dev.architectury.mixin.fabric.MixinServerPlayer (#architectury:architectury.mixins.json)
		org.quiltmc.qsl.entity_events.mixin.ServerPlayerEntityMixin (#quilt_entity_events:quilt_entity_events.mixins.json)
		org.quiltmc.qsl.worldgen.dimension.mixin.ServerPlayerEntityMixin (#quilt_dimension:quilt_dimension.mixins.json)
		com.natamus.collective.fabric.mixin.ServerPlayerMixin (#collective:collective-fabric.mixins.json)
		net.kyrptonaught.customportalapi.mixin.ServerPlayerMixin (#customportalapi:customportalapi.mixins.json)
		dev.architectury.mixin.fabric.LivingDeathInvoker (#architectury:architectury.mixins.json)
		org.quiltmc.qsl.registry.mixin.ServerPlayerEntityMixin (#quilt_registry:quilt_registry.mixins.json)
		net.fabricmc.fabric.mixin.screenhandler.ServerPlayerEntityMixin (#quilted_fabric_screen_handler_api_v1:quilted_fabric_screen_handler_api_v1.mixins.json)
		net.fabricmc.fabric.mixin.entity.event.ServerPlayerEntityMixin (#quilted_fabric_entity_events_v1:quilted_fabric_entity_events_v1.mixins.json)
		net.fabricmc.fabric.mixin.container.ServerPlayerEntityAccessor (#quilted_fabric_containers_v0:quilted_fabric_containers_v0.mixins.json)
		org.quiltmc.qsl.command.mixin.ServerPlayerEntityMixin (#quilt_command:quilt_command.mixins.json)
		net.mehvahdjukaar.moonlight.core.mixins.fabric.ServerPlayerAccessor (#moonlight:moonlight.mixins.json)
		potionstudios.byg.mixin.common.entity.MixinServerPlayer (#byg:byg.mixins.json)
		com.yungnickyoung.minecraft.yungsapi.mixin.ServerPlayerEntityTickMixin (#yungsapi:yungsapi.mixins.json)
	net.minecraft.class_3244:
		org.quiltmc.qsl.networking.mixin.ServerPlayNetworkHandlerMixin (#quilt_networking:quilt_networking.mixins.json)
		com.natamus.collective.fabric.mixin.ServerGamePacketListenerImplMixin (#collective:collective-fabric.mixins.json)
		net.bettercombat.mixin.ServerPlayNetworkHandlerMixin (#bettercombat:bettercombat.mixins.json)
		lol.bai.badpackets.impl.mixin.MixinServerGamePacketListenerImpl (#badpackets:badpackets.mixins.json)
	net.minecraft.class_2535:
		org.quiltmc.qsl.networking.mixin.ClientConnectionMixin (#quilt_networking:quilt_networking.mixins.json)
		lol.bai.badpackets.impl.mixin.MixinConnection (#badpackets:badpackets.mixins.json)
	net.minecraft.server.MinecraftServer:
		org.quiltmc.qsl.lifecycle.mixin.MinecraftServerMixin (#quilt_lifecycle_events:quilt_lifecycle_events.mixins.json)
		com.chaosthedude.explorerscompass.mixins.MinecraftServerMixin (#explorerscompass:explorerscompass.mixins.json)
		potionstudios.byg.mixin.server.MixinMinecraftServer (#byg:byg.mixins.json)
		org.quiltmc.qsl.base.mixin.MinecraftServerMixin (#quilt_base:quilt_base.mixins.json)
		potionstudios.byg.mixin.access.MinecraftServerAccess (#byg:byg.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftServerMixin (#collective:collective-fabric.mixins.json)
		org.quiltmc.qsl.worldgen.biome.mixin.MinecraftServerMixin (#quilt_biome:quilt_biome.mixins.json)
		org.quiltmc.qsl.worldgen.biome.mixin.modification.MinecraftServerMixin (#quilt_biome:quilt_biome.mixins.json)
		com.chaosthedude.naturescompass.mixins.ServerMixin (#naturescompass:naturescompass.mixins.json)
		net.fabricmc.fabric.mixin.message.MinecraftServerMixin (#quilted_fabric_message_api_v1:quilted_fabric_message_api_v1.mixins.json)
		org.betterx.worlds.together.mixin.common.MinecraftServerMixin (#bclib:together.mixins.common.json)
		org.betterx.bclib.mixin.common.MinecraftServerMixin (#bclib:bclib.mixins.common.json)
		org.betterx.worlds.together.mixin.common.MinecraftServerMixinLate (#bclib:together.mixins.common.json)
		terrablender.mixin.MixinMinecraftServer (#terrablender:terrablender_fabric.mixins.json)
		org.quiltmc.qsl.resource.loader.mixin.MinecraftServerMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
	net.minecraft.class_1132:
		dev.architectury.mixin.fabric.client.MixinIntegratedServer (#architectury:architectury.mixins.json)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 82
	Entity Name: lartts
	Entity's Exact location: 10.83, 66.14, 635.67
	Entity's Block location: World: (10,66,635), Section: (at 10,2,11 in 0,4,39; chunk contains blocks 0,-64,624 to 15,319,639), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Entity's Momentum: 0.00, -0.65, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 82
	Entity Name: lartts
	Entity's Exact location: 10.83, 66.14, 635.67
	Entity's Block location: World: (10,66,635), Section: (at 10,2,11 in 0,4,39; chunk contains blocks 0,-64,624 to 15,319,639), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Entity's Momentum: 0.00, -0.65, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
```

### Other Mods

```shell
AdditionalStructures
AmbientSounds
architectury
armorpointspp
AttributeFix
auditory
awesomedungeonend
badpackets
bbs
bettercombat
bsvsb
catalogue
clothconfig
Clumps
collective
combatroll
comet
Controlling
CorgiLib
CraftyCrashes
CreativeCore
cullclouds
dawnAPI
dragondropselytra
dragonfight
dragonloot
DripSounds
DungeonsArise
dynamiccrosshair
dynamiccrosshaircompat
DynamicSurroundingsRemastered
EndAdditions
endereyes
enderism
enderite
endermantic
enderscape
endportalrecipe
entityculling
everycomp
ExplorersCompass
explorify
extrasounds
endremastered
thelostcastle
fallingleaves
ferritecore
FractalPortals
geckolib
hitmarker
illuminations
improvedend
indium
iris
Jade
justendanchor
kelvinsbetterplayeranimations
lazydfu
letmedespawn
libraryferret
mantori
menulogue
midnightlib
mixintrace
modmenu
moonlight
moreculling
MouseTweaks
NaturesCompass
Nullscape
BYG
playeranimationlib
PresenceFootsteps
promenade
purpeille
quiltgoslightlyfasterlol
reesessodiumoptions
repurposedstructures
respawningshulkers
rei
sodiumextra
sodium
soundphysics
moreendcities
starlight
TerraBlender
totwadditions
TravelersTitles
uselessreptile
visuality
YetAnotherConfigLib
YungsApi
YungsBetterStrongholds
```

**Comment by StumblingGamer** [comment] 2023-03-26 01:37
I have this same error when entering the portal - crashes whole server, and I can't join after.

**Comment by Mithrandir-Earendur** [comment] 2023-03-27 23:02
Same error, crash upon entering portal, sort of loads end but crashes before loading the world data. Log here: https://mclo.gs/hA19cKf

**Comment by Varlanou** [comment] 2023-03-28 20:23
This is the same issue I have mentioned in issue #186. Just a note for the Devs so they can link the issues. At least the initial part of the error log is the same, though I used far less mods when mine crashed.

**Comment by thebebee** [comment] 2023-03-31 05:54
+1 getting this as well, any fixes so far?

**Comment by Purplo262** [comment] 2023-03-31 10:52
I can confirm I am also having this problem on my 1.19.2 Fabric multiplayer server.

**Comment by wezik** [comment] 2023-04-04 19:46
same issue here

**Comment by ghost** [comment] 2023-04-05 10:40
same issue here, any news on it?

**Comment by StumblingGamer** [comment] 2023-04-05 12:29
I found a temporary work around. 
For me the glitch was a conflict between Byg and BetterEnd.  

Edit: In the *betterEnd* config (maybe both), I disabled the chorus forest biome, and that fixed my issue.  (i did delete the world folder and restart, but you may be able to get away without deleting.  Maybe restore a backup from before entering the end, disable the biome, and then restart).

**Comment by thebebee** [comment] 2023-04-05 14:03
> I found a temporary work around.

this worked for me, however, end cities no longer generated. i did not try to delete the world folder though.

**Comment by ghost** [comment] 2023-04-05 16:13
i set chorus_forest weight to 0 in end-biomes config but i still get the same issue mentioned here :/

**Comment by wezik** [comment] 2023-04-05 18:00
@Kinami37 disable it in both byg and better end configs

**Comment by ghost** [comment] 2023-04-06 08:17
ah, i tried the reverse and only disabled it in the betterEnd, works now

**Comment by kalethemonster** [comment] 2023-04-07 06:20
> I found a temporary work around. For me the glitch was a conflict between Byg and BetterEnd.

i tried this, but now the world itself just kicks me, not even crashes, an im a bit reluctant to reset the end as i've already started a big build on the main island. i could world edit copy the whole area then put it back,,, but im a bit reluctant to do that as my world is one i play on lan with firends via hamatch and we'd all have to be in agreement about cheating to do that. (as the world is in survival)

**Comment by StumblingGamer** [comment] 2023-04-07 16:21
> > I found a temporary work around. For me the glitch was a conflict between Byg and BetterEnd.
> 
> i tried this, but now the world itself just kicks me, not even crashes, an im a bit reluctant to reset the end as i've already started a big build on the main island. i could world edit copy the whole area then put it back,,, but im a bit reluctant to do that as my world is one i play on lan with firends via hamatch and we'd all have to be in agreement about cheating to do that. (as the world is in survival)


How did you get into the end to start a build if you were experiencing this issue, and furthermore... If you were able to build in the end and didn't have this issue, why would you attempt the workaround?

Every time I had this issue, the game would kick me on join, and then the server would crash.  Had to either delete the world folder, or... Restore a backup of the server from prior to entering the end.

**Comment by thebebee** [comment] 2023-04-07 16:57
> > > I found a temporary work around. For me the glitch was a conflict between Byg and BetterEnd.
> > 
> > 
> > i tried this, but now the world itself just kicks me, not even crashes, an im a bit reluctant to reset the end as i've already started a big build on the main island. i could world edit copy the whole area then put it back,,, but im a bit reluctant to do that as my world is one i play on lan with firends via hamatch and we'd all have to be in agreement about cheating to do that. (as the world is in survival)
> 
> How did you get into the end to start a build if you were experiencing this issue, and furthermore... If you were able to build in the end and didn't have this issue, why would you attempt the workaround?
> 
> Every time I had this issue, the game would kick me on join, and then the server would crash. Had to either delete the world folder, or... Restore a backup of the server from prior to entering the end.

i think “main island” referred to the overworld? unless they were playing on an older version, updated, caused the issue

**Comment by StumblingGamer** [comment] 2023-04-07 17:14
> i think “main island” referred to the overworld? unless they were playing on an older version, updated, caused the issue

Maybe?  Either way... If the biome in question has generated, or maybe even just "the_end"... I don't think there's a way around this bug. At least... Not that I've found.  :/

Hope it gets updated soon.  :)

**Comment by StumblingGamer** [comment] 2023-04-07 17:19
> > I found a temporary work around. For me the glitch was a conflict between Byg and BetterEnd.
> 
> i tried this, but now the world itself just kicks me, not even crashes, an im a bit reluctant to reset the end as i've already started a big build on the main island. i could world edit copy the whole area then put it back,,, but im a bit reluctant to do that as my world is one i play on lan with firends via hamatch and we'd all have to be in agreement about cheating to do that. (as the world is in survival)


Take a backup of the end... Delete the end, try joining again?

**Comment by kalethemonster** [comment] 2023-04-08 08:09
> > > > I found a temporary work around. For me the glitch was a conflict between Byg and BetterEnd.
> > > 
> > > 
> > > i tried this, but now the world itself just kicks me, not even crashes, an im a bit reluctant to reset the end as i've already started a big build on the main island. i could world edit copy the whole area then put it back,,, but im a bit reluctant to do that as my world is one i play on lan with firends via hamatch and we'd all have to be in agreement about cheating to do that. (as the world is in survival)
> > 
> > 
> > How did you get into the end to start a build if you were experiencing this issue, and furthermore... If you were able to build in the end and didn't have this issue, why would you attempt the workaround?
> > Every time I had this issue, the game would kick me on join, and then the server would crash. Had to either delete the world folder, or... Restore a backup of the server from prior to entering the end.
> 
> i think “main island” referred to the overworld? unless they were playing on an older version, updated, caused the issue

i started the world with less mods and slowly added more, byg and better end being some of the more recent ones and i'd already started my end build before adding them, i was going to new outer end chunks to do end busting, which is where i encountered the bug, in which the world just crashed. inrespose to (and it sent me back several hundred blocks when i re-loaded)

**Comment by begriefed** [comment] 2023-04-11 02:33
config > betterend > biomes.json

"chorus_forest": {
      "enabled [default: true]": false

chorus_forest seems to be the only allowed spawn biome for end cities as they cease to be generated when chorus forests are removed.

.structure(BiomeTags.HAS_END_CITY)  is not being applied to vanilla biomes?

config > bclib > biomes.json lists old_bulbis_gardens and allows to change generation chance, but setting that to 0 does not fix this feature-order-cycle issue.  It is not listed in the betterend biomes.json

https://misode.github.io/guides/feature-order-cycle/ seems to discuss the fix for this issue.  It seems that some feature is just out of order.

**Comment by begriefed** [comment] 2023-04-11 15:46
I think I found the fix that is needed.  

It looks like the last commit, here, was a reformat.

https://github.com/quiqueck/BetterEnd/blob/1.19/src/main/java/org/betterx/betterend/world/biome/land/ChorusForestBiome.java

 .feature(EndFeatures.PURPLE_POLYPORE)
                .feature(Decoration.VEGETAL_DECORATION, EndPlacements.CHORUS_PLANT)

PURPLE_POLYPORE is listed before VEGETAL_DECORATION in the ChorusForestBiome code.

https://github.com/quiqueck/BetterEnd/blob/1.19/src/main/java/org/betterx/betterend/integration/byg/biomes/OldBulbisGardens.java

The (much longer code; not pasting it here) OldBulbisGardens code lists VEGETAL_DECORATION first.  I am not sure which one needs their order reversed to not conflict with any other biomes.  I haven't been able to find another biome that contains both of these features to see which order is used, though VEGETAL_DECORATION is listed after the other features in the other byg integration biome, NightshadeRedwoods.java

Moving the OldBulbisGardens "builder.feature" code above the for loop that hard codes in trees may be a simple fix (or may break everything, what do I know)

I hope this is of some help and is not just muddying up the comments.

**Comment by bl4d3tv** [comment] 2023-04-13 14:49
Should be fixed in #196,  thanks @begriefed for pointing me in the right direction, it was that simple after all.
Hopefully it gets merged soon, in the meantime if someone wants a build with the fix let me know.

**Comment by ambientNexus** [comment] 2023-04-13 19:05
> Hopefully it gets merged soon, in the meantime if someone wants a build with the fix let me know.

Would you mind uploading it here or adding it as a release for your fork?

**Comment by bl4d3tv** [comment] 2023-04-13 19:13
> Would you mind uploading it here or adding it as a release for your fork?

Just uploaded it as the latest release, you can find it here: https://github.com/bl4d3tv/BetterEnd/releases/tag/2.1.4

**Closed as completed** 2023-05-16 15:28 UTC
