### ISSUE TITLE
[Bug] End Pillar Generated in Void

### ISSUE THREAD

**Issue by NolanHewitt** [quiqueck/BetterEnd#274] opened 2023-07-21 03:36 UTC
### What happened?

End Pillar spawned in the void

### BetterEnd

2.1.6

### BCLib

2.1.7

### Fabric API

0.76.0

### Fabric Loader

0.14.21

### Minecraft

1.19.2

**Comment by NolanHewitt** [comment] 2023-07-21 03:37
![huge_2023-07-20_22 29 25-min](https://github.com/quiqueck/BetterEnd/assets/52480898/24e2b7e9-9440-4e60-bdee-8a256387f803)

**Comment by quiqueck** [comment] 2023-07-22 11:41
Do you happen to have the seed for this world? And (if it isn't too much trouble) the `data/worlds_together.nbt` from that worlds folder.

**Comment by VladHellish** [comment] 2023-12-06 13:37
Hi! Seems like BetterEnd breaks world height map. I'm experiencing similar problems with different structure mods.

**Comment by quiqueck** [comment] 2023-12-20 12:07
Duplicate of #319

**Closed as completed by quiqueck** 2023-12-20 12:07 UTC
Labels: 🥈 duplicate
