### ISSUE TITLE
[Crash] Server crashes on newest better end update

### ISSUE THREAD

**Issue by SylvaGamer** [quiqueck/BetterEnd#241] opened 2023-06-21 14:09 UTC
Server crashes due to errors in better end, my client can run just fine. 
I'm trying to update the server from better end 4.0.3 and related bclib and better nether to their updated versions. my client launches 0 issues but when i try to start the server it crashes without a crash report so their is the log from when this happened.
fabric loader: 0.14.21
fabric-api: 0.83.0

log:
[2023-06-21-7.log](https://github.com/quiqueck/BetterEnd/files/11818568/2023-06-21-7.log)
```
[08:48:04] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[08:48:04] [ForkJoinPool-1-worker-6/WARN]: The mod "wunderlib" contains invalid entries in its mod json:
- Unsupported root entry "modmenu" at line 26 column 12
[08:48:04] [ForkJoinPool-1-worker-1/WARN]: Mod ironfish_mr uses the version 1-mcmeta-4_1.20 which isn't compatible with Loader's extended semantic version format (Invalid prerelease string 'mcmeta-4_1.20'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[08:48:04] [ForkJoinPool-1-worker-1/WARN]: The mod "wunderlib" contains invalid entries in its mod json:
- Unsupported root entry "modmenu" at line 26 column 12
[08:48:05] [main/INFO]: Loading 115 mods:
	- additionallanterns 1.0.4-a
	- all_the_fan_made_discs 0.5.6
	- antilogout 1.1.3
	   |-- config2brigadier 1.2.3
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- appleskin 2.5.0+mc1.20
	- bclib 3.0.9
	   \-- wunderlib 1.1.2
	- betterend 4.0.5
	- betternether 9.0.6
	- bettersafebed 1.20-8
	- carpet 1.4.112+v230608
	- carpet-autocraftingtable 1.4.57
	- carpet-extra 1.4.112
	- cloth-config 11.0.98
	   \-- cloth-basic-math 0.6.1
	- clutter 1.20-0.3.1
	- collective 6.57
	- dungeons_andtaverns_mr 1-v2.1.1
	- enchanttweaker 1.4.3+mc1.20-1.20.1
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- fabric-api 0.83.0+1.20
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b27
	   |-- fabric-block-api-v1 1.0.9+e022e5d127
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
	   |-- fabric-command-api-v1 1.2.32+f71b366f27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-commands-v0 0.2.49+df3654b327
	   |-- fabric-containers-v0 0.1.61+df3654b327
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b27
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
	   |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b27
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b27
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
	   |-- fabric-item-api-v1 2.1.26+b3afc78b27
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
	   |-- fabric-keybindings-v0 0.2.34+df3654b327
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b27
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c627
	   |-- fabric-message-api-v1 5.1.6+b3afc78b27
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
	   |-- fabric-models-v0 0.3.35+b3afc78b27
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b27
	   |-- fabric-networking-v0 0.3.48+df3654b327
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
	   |-- fabric-particles-v1 1.0.28+b3afc78b27
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b27
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b327
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
	   |-- fabric-rendering-v0 1.1.47+df3654b327
	   |-- fabric-rendering-v1 3.0.6+b3afc78b27
	   |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b27
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b27
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
	- fabricloader 0.14.21
	- fallingtree 4.0.0
	- foodplusid 2.1+1.20
	- friendsandfoes 1.9.0
	- geckolib 4.2
	   \-- com_eliotlash_mclib_mclib 20
	- grindenchantments 3.1.2+1.20
	   \-- codec-config-api 1.0.2+1.19.3
	- headfix 1.2.2
	- hoetweaks 3.2
	- htm 1.1.9
	   |-- common-protection-api 1.0.0
	   \-- server_translations_api 2.0.0-beta.2+1.19.4-pre2
	        \-- packet_tweaker 0.3.1+23w06a
	- incantationem 1.2.1+1.20
	   \-- yet_another_config_lib_v3 3.0.1+1.20
	        |-- com_twelvemonkeys_common_common-image 3.9.4
	        |-- com_twelvemonkeys_common_common-io 3.9.4
	        |-- com_twelvemonkeys_common_common-lang 3.9.4
	        |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	        \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
	- inventorymanagement 1.3.1
	- ironfish_mr 1-mcmeta-4_1.20
	- jade 11.0.3
	- jamlib 0.6.0+1.20
	- java 17
	- journeymap 5.9.7
	   \-- journeymap-api-fabric 1.20-1.9-fabric-SNAPSHOT
	- justmobheads 7.1
	- labellingcontainers 1.2.0
	- lithium 0.11.2
	- mcserverdescription 4.0.0+1.20
	- midnightlib 1.4.0
	- minecraft 1.20
	- minitweaks 1.4.0
	- mob_captains_mr 1-v2.1.2
	- qu-enchantments 1.3.5-1.20
	   \-- mm 2.3
	- redstonebits 1.10.2
	- refined_advancements_mr 1.0.3
	- repurposed_structures 7.0.0+1.20-fabric
	- rightclickharvest 3.2.2+1.19.x-1.20-fabric
	- sculk_expansion_mr 1.0.1
	- servercore 1.3.6+1.20
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- fabric-api-base 0.4.29+b04edc7a27
	   |-- fabric-command-api-v2 2.2.11+b3afc78b27
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.1+1.20
	- sessility 0.2.3
	- supermartijn642corelib 1.1.9
	- wilderwild 2.0.3-Fabric+1.20
	   |-- caffeineconfig 1.0.0+1.17
	   |-- frozenlib 1.2.4-Fabric+1.20
	   |    \-- blue_endless_jankson 1.2.2
	   \-- nbtcrafting 2.2.3+mc1.20
	        |-- fabric-api-base 0.4.29+b04edc7a27
	        \-- fabric-networking-api-v1 1.3.8+b3afc78b27
	- wunderreich 6.0.3
[08:48:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Minecraft%20Server/Desktop/NEWServer/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[08:48:05] [main/INFO]: Compatibility level set to JAVA_17
[08:48:05] [main/WARN]: Reference map 'ATFMD-refmap.json' for atfmd.mixins.json could not be read. If this is a development environment you can ignore this message
[08:48:05] [main/WARN]: Reference map 'codec-config-api-refmap.json' for codec-config-api.mixins.json could not be read. If this is a development environment you can ignore this message
[08:48:05] [main/INFO]: [EnchantTweaker] Mod enabled! Enabling mixins...
[08:48:05] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 1 override(s) found
[08:48:05] [main/INFO]: [EnchantTweaker] [COMPAT] BowInfinityFixMixin disabled. Reason: MoreInfinityMixin is enabled and takes precedence
[08:48:06] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[08:48:12] [main/WARN]: @Redirect conflict. Skipping minitweaks.mixins.json:mob.dragon.block_damage.EnderDragonEntityMixin from mod minitweaks->@Redirect::destroyType(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Z)Z with priority 999, already redirected by htm.mixins.json:events.EnderDragonEntityMixin from mod htm->@Redirect::mobTick(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Z)Z with priority 1000
[08:48:12] [main/WARN]: Method overwrite conflict for getConnection in fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric-networking-api-v1, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.
[08:48:13] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[08:48:13] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[08:48:13] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[08:48:13] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[08:48:13] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[08:48:13] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[08:48:13] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[08:48:13] [main/WARN]: [bclib] Recipe betternether:bone_block_bone_button only takes in a single item and should be shapeless
[08:48:14] [main/INFO]: Trying to read config file...
[08:48:14] [main/INFO]: A config file was found, loading it..
[08:48:14] [main/INFO]: Successfully loaded config file.
[08:48:14] [main/INFO]: [rightclickharvest] Initializing VersionUtils
[08:48:14] [main/INFO]: [rightclickharvest] VersionUtils initialized successfully
[08:48:14] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[08:48:14] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config betterend.entities to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config betterend.blocks to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config betterend.items to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config betterend.biomes to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config betterend.recipes to auto sync (file hash)
[08:48:14] [main/INFO]: [bclib] Added Config betterend.enchantments to auto sync (file hash)
[08:48:20] [main/INFO]: [betternether] =^..^=    BetterNether for 1.19    =^..^=
[08:48:21] [main/INFO]: Registering Mod Items for clutter
[08:48:21] [main/INFO]: Registering ModBlocks for clutter
[08:48:21] [main/INFO]: [STDOUT]: Registering Enchantments for clutter
[08:48:21] [main/INFO]: Loading Collective version 6.57.
[08:48:21] [main/INFO]: Loaded C2B lib.
[08:48:21] [main/INFO]: [EnchantTweaker] Ready to go! Applied 51 Mixins.
[08:48:21] [main/INFO]: [jamlib] Mod initialized!
[08:48:21] [main/INFO]: Initializing ServerSide Packet Registries
[08:48:21] [main/INFO]: Initializing...
[08:48:21] [main/INFO]: Definitely not up to no good
[08:48:21] [main/INFO]: Finished validating config for qu-enchantments
[08:48:21] [ForkJoinPool.commonPool-worker-1/INFO]: [Friends&Foes] An update is available! You are using 1.9.0 version, but the latest version is 1.9.1.
[08:48:21] [main/INFO]: Registering ModEnchantments for qu-enchantments
[08:48:21] [main/INFO]: Registering ModBlocks for qu-enchantments
[08:48:21] [main/INFO]: Registering ModItems for qu-enchantments
[08:48:21] [main/INFO]: Finished registering Mod Particles for qu-enchantments
[08:48:21] [main/INFO]: Finished Initializing qu-enchantments
[08:48:21] [main/INFO]: Redstone Bits config version 1
[08:48:21] [main/INFO]: [jamlib] Registered config for rightclickharvest
[08:48:21] [main/INFO]: [rightclickharvest] Mod initialized!
[08:48:21] [main/INFO]: [ServerCore] Loaded V1.3.6+1.20!
[08:48:21] [main/INFO]: Started measuring WilderWild
[08:48:21] [main/INFO]: Applying DataFixes for Wilder Wild with Data Version 14
[08:48:21] [main/INFO]: DataFixes for Wilder Wild have been applied
[08:48:22] [main/INFO]: Adding Music And Ambience To Biomes for wilderwild
[08:48:22] [main/INFO]: WilderWild took 96188100 nanoseconds
[08:48:22] [main/INFO]: Discarding Recipe for wunderreich:whisperer_blank
[08:48:22] [main/INFO]: Discarding Recipe for wunderreich:whisper_imprinter
[08:48:22] [main/INFO]: Adding GameRule 'wunderreichDoNotDespawnWithNameTag' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'whispersDurability' (default: 20)
[08:48:22] [main/INFO]: Adding GameRule 'whispersTrainedDurability' (default: 40)
[08:48:22] [main/INFO]: Adding GameRule 'whispersMinXPMultiplier' (default: 75)
[08:48:22] [main/INFO]: Adding GameRule 'whispersMaxXPMultiplier' (default: 100)
[08:48:22] [main/INFO]: Adding GameRule 'wunderreichAllowLibrarianSelection' (default: false)
[08:48:22] [main/INFO]: Adding GameRule 'wunderreichAllowTradesCycling' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderreichCyclingNeedsWhisperer' (default: false)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteRedstonePowerWhenOpened' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteAnalogRedstoneOutput' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteShowColored' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteAllowNetworks' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteAllowNamedNetworks' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteCanColor' (default: true)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteChangeNetworkCost' (default: 1)
[08:48:22] [main/INFO]: Adding GameRule 'wunderkisteChunkLoaderRadius' (default: 1)
[08:48:22] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabricServer.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:88) ~[better-end-4.0.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:88) ~[better-end-4.0.5.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
```
Mods:
[modslist.txt](https://github.com/quiqueck/BetterEnd/files/11818570/modslist.txt)
```
additionallanterns-1.0.4a-fabric-mc1.20
antilogout-1.1.3
appleskin-fabric-mc1.20-2.5.0
ATFMD-0.5.6-1.20
bclib-3.0.9
better-end-4.0.5
better-end-4.0.5
better-nether-9.0.5
bettersafebed-fabric-1.20-8
carpet-autocraftingtable-1.20-1.4.112
carpet-extra-1.20-1.4.112
cloth-config-11.0.98-fabric
clutter-1.20-0.3.1
collective-1.20.0-6.57
DisableInsecureChatToast-mc1.20-1.1.0
dungeons-and-taverns-v2.1.1
enchanttweaker-1.4.3+mc1.20-1.20.1
fabric-api-0.83.0+1.20
fabric-carpet-1.20-1.4.112+v230608
FallingTree-1.20-4.0.0
food-plus-2.1+1.20
friendsandfoes-fabric-mc1.20-1.9.0
geckolib-fabric-1.20-4.2
grind-enchantments-3.1.2+1.20
head-name-fix-1.20-1.2.2
hoetweaks-1.20.0-3.2
htm-1.1.9
incantationem-1.2.1+1.20
inventorymanagement-1.3.1+1.20
ironfish-mcmeta-4_1.20
Jade-1.20-fabric-11.0.3
jamlib-0.6.0+1.20
journeymap-1.20-5.9.7-fabric
justmobheads-1.20.0-7.1
labellingcontainers-1.2.0
lithium-fabric-mc1.20-0.11.2
mc-server-description-4.0.0+1.20
midnightlib-fabric-1.4.0
minitweaks-1.20-1.4.0
mob-captains-v2.1.2
qu-enchantments-1.3.5-1.20
redstone-bits-1.10.2+fabric-mc1.20
refined-advancements-1.0.3
repurposed_structures-7.0.0+1.20-fabric
right-click-harvest-3.2.2+1.19.x-1.20-fabric
Sculk_Expansion_v1.0.1
servercore-fabric-1.3.6+1.20
sessility-0.2.3
supermartijn642corelib-1.1.9-fabric-mc1.20
WilderWild-2.0.3-Fabric+1.20
wunderreich-6.0.3
```

**Comment by quiqueck** [comment] 2023-06-21 19:27
Duplicate of  #242

I just uploaded a fixed Version (4.0.6).

**Closed as completed by quiqueck** 2023-06-21 19:27 UTC
Labels: 🥈 duplicate
