### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FoxesHouse** [quiqueck/BetterEnd#37] opened 2022-07-11 16:08 UTC
### What happened?

The game crash is you open the End Smelter.

### BetterEnd

2.0.6

### BCLib

2.0.12

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Sorry :(

Time: 7/11/22, 5:54 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at org.betterx.betterend.blocks.entities.EndStoneSmelterBlockEntity.method_5465(EndStoneSmelterBlockEntity.java:234)
	at net.minecraft.class_2624.createMenu(class_2624.java:92)
	at net.minecraft.class_3222.method_17355(class_3222.java:1040)
	at org.betterx.betterend.blocks.EndStoneSmelter.openScreen(EndStoneSmelter.java:79)
	at org.betterx.betterend.blocks.EndStoneSmelter.method_9534(EndStoneSmelter.java:71)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:963)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1115)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:menu / betterend:end_stone_smelter])
	at net.minecraft.class_2370.method_40274(class_2370.java:81)
	at net.minecraft.class_2370.method_31051(class_2370.java:91)
	at net.minecraft.class_2370.method_10273(class_2370.java:87)
	at net.minecraft.class_2370.method_10272(class_2370.java:135)
	at net.minecraft.class_2378.method_39197(class_2378.java:508)
	at net.minecraft.class_2378.method_10230(class_2378.java:504)
	at net.fabricmc.fabric.api.screenhandler.v1.ScreenHandlerRegistry.registerSimple(ScreenHandlerRegistry.java:90)
	at org.betterx.betterend.client.gui.EndStoneSmelterScreenHandler.<clinit>(EndStoneSmelterScreenHandler.java:29)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.4.0-109-generic
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1254533344 bytes (1196 MiB) / 2306867200 bytes (2200 MiB) up to 2306867200 bytes (2200 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7F72 24-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 48
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129831.55
	Virtual memory used (MB): 205506.88
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 363.93
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=300M -Xmx2200M -Xms1100M
	Fabric Mods: 
		adventurez: AdventureZ 1.4.14
		archeology: CapsLock Archeology Mod 0.1.9
			midnightlib: MidnightLib 0.5.2
		architectury: Architectury 5.8.29
		bclib: BCLib 2.0.12
		betteranimalsplus: Better Animals Plus 1.19-11.0.6
		betterend: Better End 2.0.6
		betternether: Better Nether 7.0.6
		byg: Oh The Biomes You'll Go 2.0.0.6
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		hwg: Happiness is a Warm Gun 1.2.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.8.5
			journeymap-api-fabric: JourneyMap API 1.19-1.8-fabric-SNAPSHOT
		lithium: Lithium 0.8.1
		mca: Minecraft Comes Alive 7.3.4+1.19
		mcdw: MC Dungeons Weapons 4.4.0-1.19
			enchant_giver: Enchant Giver 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		minecraft: Minecraft 1.19
		roughlyenoughitems: Roughly Enough Items 9.1.504
		terrablender: TerraBlender 2.0.0.120
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
	Server Running: true
	Player Count: 2 / 20; [class_3222['FoxyPirate337'/791, l='ServerLevel[world]', x=-2249.73, y=63.00, z=77.42], class_3222['Gjanlo'/1033, l='ServerLevel[world]', x=-2250.42, y=63.00, z=76.79]]
	Data Packs: vanilla, Fabric Mods, file/Better-Villages.zip (incompatible), file/dungeon-now-loading-v16.2-1.19.zip, file/pillager-stronghold-1-19.zip, file/New-Igloo.zip (incompatible), file/choicetheorem-overhaul-village-1-19-3-0-2.zip, file/New-Ocean-Ruins.zip (incompatible), file/splatus-mountain-villages-v1-0-2.zip, file/towns-and-towers-structure-add-on-1-7-2.zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by quiqueck** [comment] 2022-07-11 17:48
duplicate of #35

**Closed as completed by quiqueck** 2022-07-11 17:48 UTC
