### ISSUE TITLE
[Bug] Game crashes when I create new world

### ISSUE THREAD

**Issue by Tremzack** [quiqueck/BetterEnd#13] opened 2022-06-18 19:39 UTC
### What happened?

Game crashes when I try to create a new world. When I remove BetterEnd, the issue disappears. 

Please let me know if I can provide any additional information.

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.14.7

### Minecraft

1.19

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/18/22, 2:31 PM
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.1)
	at net.minecraft.tag.TagGroupLoader.mdb112ee$lambda$loadTagInject$1$1(TagGroupLoader:1055)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.tag.TagGroupLoader.handler$eod000$loadTagInject(TagGroupLoader:1053)
	at net.minecraft.tag.TagGroupLoader.loadTags(TagGroupLoader:68)
	at net.minecraft.tag.TagGroupLoader.load(TagGroupLoader:163)
	at net.minecraft.tag.TagManagerLoader.method_33181(TagManagerLoader:64)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:494)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:494)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.handler$clc000$handleWaitEventsTimeout(RenderSystem.java:1483)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1583612808 bytes (1510 MiB) / 4253024256 bytes (4056 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce GTX 1080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b80
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 104373.36
	Virtual memory used (MB): 25645.17
	Swap memory total (MB): 38912.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8096m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalbanners: AdditionalBanners 8.0.1
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.5.4+1.19
		ambientenvironment: Ambient Environment 8.0+1
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.27
		attributefix: AttributeFix 15.0.1
		awesomedungeon: Awesome Dungeon 2.0.9
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 4.2.0+0
		bclib: BCLib 2.0.5
		beaconoverhaul: Beacon Overhaul 1.7.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		bedbenefits: BedBenefits 7.0.1
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		betterend: Better End 2.0.2
		betternether: Better Nether 7.0.2
		betterthirdperson: Better Third Person 1.8.1
		bettervillage: Better Village 1.0.1
		biomeinfo: BiomeInfo 1.19-11
		biomemakeover: Biome Makeover 1.19-beta-1.5.5
		blur: Blur (Fabric) 2.5.0
		bookshelf: Bookshelf 14.0.3
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.1.0
		clear-skies: Clear Skies 2.0.93
		cleardespawn: Clear Despawn 1.1.8
		clienttweaks: Client Tweaks 8.0.0
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.2+mc.1.19
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+1
		couplings: Couplings 1.9.0+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		cull-less-leaves: Cull Less Leaves 1.0.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		darkness: True Darkness 2.0.94
		darkpaintings: DarkPaintings 11.0.2
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.5
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		eatinganimationid: Eating Animation 1.8.1
		ecologics: Ecologics 2.0.1
		effective: Effective 1.2.2
		enchdesc: EnchantmentDescriptions 11.0.4
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		expandeddelight: Expanded Delight 0.2
		extraalchemy: Extra Alchemy 1.8.3
		fabric: Fabric API 0.56.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.13+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+4a3ec384a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.8+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.7
		fallingleaves: Falling Leaves 1.12.1+1.19
		fallingtree: FallingTree 3.6.1
		farmersdelight: Farmer's Delight 1.19-0.3.0
		fishofthieves: Fish of Thieves 2.0.2
		fpsreducer: FPS Reducer 1.19-2.0.1
		friendsandfoes: Friends&Foes 1.5.1
			mm: Manningham Mills 2.3
		geckolib3: Geckolib 3.1.2
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.3
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 1.10
			omega-config: OmegaConfig 1.2.2-1.18.1
		graveyard_biomes: The Graveyard Biomes 1.2
		herdspanic: Herds Panic 1.0.6
		illuminations: Illuminations 1.10.5
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		impactfulweather: Biome Particle Weather 3.4.8
		impaled: Impaled 1.1.4
		indium: Indium 1.0.5+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		jade: Jade 7.3.1
		jamlib: JamLib 0.0.8
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.8.0
		mambience: MAmbience 5.2.0+1.19
		map_atlases: Map Atlases 1.5.0
		mavm: More Axolotl Variants Mod 1.0.8a
		mcwpaintings: Macaw's Paintings 1.0.3
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.0
		moretotems: More Totems 2.11.0
		morevillagers: More Villagers 4.0.1
		morezombievillagers-fabric: More Zombie Villagers (Fabric) 1.7
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.9.1+mc1.19-pre1
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		naturalist: Naturalist 2.0.1
		nears: Nears 1.1.8
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		npcvariety: NPC Variety 2.2.1
		onsoulfire: On Soul Fire 1.19-2
		overweight_farming: Overweight Farming 1.19-1.4.2-fabric
		oxidized: Oxidized 1.7.0
		paintings: Paintings++ 10.0.0.0
		presencefootsteps: Presence Footsteps 1.6.0
			kirin: Kirin UI 1.11.0
		realisticfirespread: Realistic Fire Spread 1.19-2
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		repurposed_structures: Repurposed Structures 6.0.4+1.19
		rightclickharvest: Right Click Harvest 2.1.1
		roughlyenoughitems: Roughly Enough Items 9.0.491
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		saplanting: Saplanting fabric-1.19-1.1.2+fix-1
		satin: Satin 1.8.0
		sextant: Immersive Travel Overhaul 1.2
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.19
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		spark: spark 1.9.13
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spellbound: Spellbound 1.9.2
		spyglass-improvements: Spyglass Improvements 1.3+mc1.19+fabric
		starlight: Starlight 1.1.1+fabric.ae22326
		terrablender: TerraBlender 2.0.0.112
		terraria_paintings: terraria paintings 2.0.0
		thonkutil: ThonkUtil 2.15.2+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.0+82e731da57
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		transparent: Transparent 5.1.0
		trulytreasures: Truly Treasures 1.19-2.0.2
		villagernames: Villager Names 4.0.4
		visuality: Visuality 0.5.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.7-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.40, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, charmonium/journeyman
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: None
```

**Comment by quiqueck** [comment] 2022-06-30 07:17
I think this is a duplicate of #10
It should be fixed with the latest release of ThonkUtil. Please re-open the issue if the problem is still there after upgrading ThonkUtil.

**Closed as completed by quiqueck** 2022-06-30 07:17 UTC
Labels: 🥈 duplicate, 🧱 external
