### ISSUE TITLE
[Bug] Loading with quilt makes recipes messed up

### ISSUE THREAD

**Issue by Touch-Night** [quiqueck/BetterEnd#47] opened 2022-07-21 03:20 UTC
### What happened?

When use quilt loader to load this mod, all wood can be broken down into 9 pieces of charcoal, and 1 piece of  charcoal can make 9 pieces of charcoal
![image](https://user-images.githubusercontent.com/102669562/180122232-1d30dac3-f04d-4905-b8d8-1a68787b19b1.png)
![image](https://user-images.githubusercontent.com/102669562/180122252-0ca64f29-22e7-4325-8566-10cbe85a27af.png)
![image](https://user-images.githubusercontent.com/102669562/180122285-c549ab68-a29f-48b9-ada9-00ab55aef952.png)
![image](https://user-images.githubusercontent.com/102669562/180122364-cda5b487-dd04-4c8e-9c61-ae0a863c38cf.png)
![image](https://user-images.githubusercontent.com/102669562/180122386-46521911-000e-4346-8865-352d318c984c.png)
![image](https://user-images.githubusercontent.com/102669562/180122420-aab7a103-6bb5-4779-9091-2d2048c112d8.png)
![image](https://user-images.githubusercontent.com/102669562/180122443-bd044804-9c5d-4554-b07a-caac105af0a6.png)

### BetterEnd

2.0.9

### BCLib

2.0.16

### Fabric API

qfapi-2.0.0-beta.7_qsl-2.0.0-beta.15_fapi-0.57.0_mc-1.19

### Fabric Loader

Quilt 0.17.1-beta.6

### Minecraft

1.19

**Comment by quiqueck** [comment] 2022-07-21 08:16
Duplicate of #41

**Closed as completed by quiqueck** 2022-07-21 08:16 UTC
Labels: 🥈 duplicate

**Comment by quiqueck** [comment] 2022-07-21 08:19
also QuiltMC/quilted-fabric-api#25
