### ISSUE TITLE
[Bug] Crashed in end island

### ISSUE THREAD

**Issue by Hype3808** [quiqueck/BetterEnd#171] opened 2023-02-26 12:53 UTC
### What happened?

We explored a little bit of the outer end island after defeating the ender dragon, and after we explored several blocks away, the server starts to crash

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.74

### Fabric Loader

0.14.13

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-02-26 20:34:24
Description: Exception ticking world

java.lang.ExceptionInInitializerError
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:particle_type / betterend:glowing_sphere])
	at net.minecraft.class_2370.method_40274(class_2370.java:135)
	at net.minecraft.class_2370.method_46744(class_2370.java:141)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:70)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:66)
	at org.betterx.betterend.registry.EndParticles.register(EndParticles.java:48)
	at org.betterx.betterend.registry.EndParticles.<clinit>(EndParticles.java:15)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)

-- Affected level --
Details:
	All players: 1 total; [class_3222['xHype_'/48, l='ServerLevel[New World]', x=-403.47, y=89.00, z=-995.46]]
	Chunk stats: 2401
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (112,70,256), Section: (at 0,6,0 in 7,4,16; chunk contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5792644 game time, 2506084 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 11411 (now: false), thunder time: 122967 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 9241881984 bytes (8813 MiB) / 14487126016 bytes (13816 MiB) up to 14487126016 bytes (13816 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2487
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 30879.88
	Virtual memory used (MB): 27475.49
	Swap memory total (MB): 14626.61
	Swap memory used (MB): 725.77
	JVM Flags: 2 total; -Xms13815M -Xmx13815M
	Fabric Mods: 
		bclib: BCLib 2.2.4
		betterend: Better End 3.1.2
		betternether: Better Nether 8.1.3
		blossom-lib: BlossomLib 2.5.0+1.19.3
			server_translations_api: Server Translations API 1.4.19+1.19.3
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
		blossom-tpa: BlossomTpa 2.1.0+1.19.3
		fabric-api: Fabric API 0.74.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.0+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.14.13
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
	Server Running: true
	Player Count: 1 / 20; [class_3222['xHype_'/48, l='ServerLevel[New World]', x=-403.47, y=89.00, z=-995.46]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
betternether: Better Nether 8.1.3
blossom-lib: BlossomLib 2.5.0+1.19.3
blossom-tpa: BlossomTpa 2.1.0+1.19.3
```

**Comment by quiqueck** [comment] 2023-05-16 11:10
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:10 UTC
