### ISSUE TITLE
[Bug] Betterend slabs render 1.21

### ISSUE THREAD

**Issue by Dbbtop** [quiqueck/BetterEnd#422] opened 2024-07-05 04:56 UTC
### What happened?

upper slab is rendered as the lower one 
![image](https://github.com/quiqueck/BetterEnd/assets/149936791/ee93de3e-5e11-446e-9fb3-a60019b17f7e)
![image](https://github.com/quiqueck/BetterEnd/assets/149936791/36dd2773-741c-43ce-b2d7-e4b3c31d5ba4)
and incorrect generation of signs
![image](https://github.com/quiqueck/BetterEnd/assets/149936791/2dc859d7-e0e6-4edb-8d44-2933d6c2f1b5)

### BetterEnd

21.0.2

### BCLib

21.0.5

### Fabric API

0.100.4

### Fabric Loader

0.15.11

### Minecraft

1.20.4

**Comment by OpenBagTwo** [comment] 2024-07-28 15:55
This is due to WorldWeaver's datagen not yet implementing [model / blockstate generation](https://fabricmc.net/wiki/tutorial:datagen_model) and so is essentially a dupe of #431

**Comment by OpenBagTwo** [comment] 2024-07-28 16:51
From my testing, slabs and stairs now render correctly after 2715665aa8a652484f7b56abdd6d82a2d0d737a1 but not some directional blocks (namely thallasium bars).

**Comment by OpenBagTwo** [comment] 2024-07-30 23:53
@Dbbtop can you confirm that this is fixed now in the new 21.0.6 and, if so, close the issue?

**Closed as completed** 2024-07-31 06:15 UTC
