### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SeniorGatos** [quiqueck/BetterEnd#98] opened 2022-10-17 19:03 UTC
### What happened?

Whenever I try to craft the thellasium blade It does not let me switch between other items to craft. the only thing I can craft is the axe head.

### BetterEnd

2.0x

### BCLib

2.0x

### Fabric API

0.5.

### Fabric Loader

0.14x

### Minecraft

1.19.2

**Comment by Necrontyrr** [comment] 2022-10-18 21:01
It works for me.
Make sure you are using the latest versions of everything. For 1.19.2 it is BCLib 2.1.2 and BE 2.1.1. Also Fabric API 0.63.

**Comment by SeniorGatos** [comment] 2022-10-19 02:29
Everything is up to date according to those versions. Still not able to
switch inside the anvil sadly

**Comment by Necrontyrr** [comment] 2022-10-19 21:08
You should attach a log or mod list
Probably is related to this https://github.com/Fuzss/easyanvils/issues/3

**Comment by quiqueck** [comment] 2022-10-25 22:24
May be a duplicate of #100

**Closed as completed** 2022-10-25 22:24 UTC
