### ISSUE TITLE
Game keeps crashing when trying to start[Bug] 

### ISSUE THREAD

**Issue by WaterishGithub** [quiqueck/BetterEnd#61] opened 2022-08-16 19:33 UTC
### Error code -1 and it blames it on Betterend

I'm currently running 1.19.1 fabric and the error message says: The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
Exit Code: -1

Edit: same issue with better nether as well.
Here's the crash report: ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-08-16 15:25:45
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
		at org.betterx.bclib.api.v2.spawning.SpawnRuleBuilder.build(SpawnRuleBuilder.java:316)
		at org.betterx.bclib.api.v2.spawning.SpawnRuleBuilder.buildNoRestrictions(SpawnRuleBuilder.java:325)
		at org.betterx.betternether.registry.NetherEntities.register(NetherEntities.java:289)
		at org.betterx.betternether.BetterNether.onInitialize(BetterNether.java:38)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
		... 13 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
	at org.betterx.bclib.api.v2.spawning.SpawnRuleBuilder.build(SpawnRuleBuilder.java:316)
	at org.betterx.bclib.api.v2.spawning.SpawnRuleBuilder.buildNoRestrictions(SpawnRuleBuilder.java:325)
	at org.betterx.betterend.registry.EndEntities.register(EndEntities.java:89)
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:41)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more

I have no idea why this is happening, and so I'm just going to remove BetterEnd while I'm playing. Can someone tell me what the problem is, and possibly the solution as well?

### BetterEnd

2.0.10

### BCLib

2.0.19

### Fabric API

0.60.0+

### Fabric Loader

0.11.0

### Minecraft

1.19.1

### Other Mods

```shell
AiotExpanded
Balm
Basic Aiot
bclib
betterend
clothconfig
diggusmaximus
fabric-api
iris
moremcmeta
more totems mod
MouseTweaks
overweight farming
sodium
iris
swingthroughgrass
TechReborn
tetra
wardenloot
wolves with armor
harvestscythes
waystones
youre in grave danger
```

**Comment by quiqueck** [comment] 2022-08-16 19:56
BetterEnd is currently not compatible with FAPI 0.60

**Comment by quiqueck** [comment] 2022-08-16 20:06
Duplicate of quiqueck/BCLib#33

**Closed as completed by quiqueck** 2022-08-16 20:06 UTC
