### ISSUE TITLE
Crash caused by incompatibility -> BetterEnd with Wilder Wilds, ONLY when moonlight lib/supplementaries is present [1.19.2]

### ISSUE THREAD

**Issue by lxly9** [quiqueck/BetterEnd#82] opened 2022-10-02 16:50 UTC
### What happened?

Game crashes when BetterEnd, Wilder Wilds and moonlight lib/supplementaries are present.

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.61.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Relevant log output

```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:41)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.IllegalStateException: Feature configuration for betterend:mossy_glowshroom can not be null!
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.buildAndRegister(BCLFeatureBuilder.java:226)
	at org.betterx.bclib.api.v3.levelgen.features.BCLFeatureBuilder.buildAndRegister(BCLFeatureBuilder.java:234)
	at org.betterx.betterend.registry.EndFeatures.registerVegetation(EndFeatures.java:1086)
	at org.betterx.betterend.registry.EndFeatures.registerVegetation(EndFeatures.java:1074)
	at org.betterx.betterend.registry.EndFeatures.<clinit>(EndFeatures.java:167)
```

**Comment by EthanRStokes** [comment] 2022-10-03 21:16
Related to quiqueck/BetterNether#48 ?

**Comment by lxly9** [comment] 2022-10-04 13:39
yup, absolutely related

**Comment by quiqueck** [comment] 2022-10-08 18:33
Duplicate of quiqueck/BetterNether#48

**Closed as completed by quiqueck** 2022-10-08 18:33 UTC
