### ISSUE TITLE
[Bug] game crashes while entering the end.

### ISSUE THREAD

**Issue by Rinigon** [quiqueck/BetterEnd#175] opened 2023-03-07 16:03 UTC
### What happened?

I'm testing out a modpack I'm making and as I entered through the end portal and starting loading it crashes.
With some research I have found out that it may have a issue with BYG Mod but I still dont know how to fix it

### BetterEnd

2.1.4

### BCLib

2.1.6

### Fabric API

0.75.1

### Fabric Loader

0.14.12

### Minecraft

1.19.2

### Relevant log output

```shell
The game crashed whilst exception generating new chunk
Error: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / betterend:chorus_forest]=net.minecraft.class_1959@6691a28e}, Reference{ResourceKey[minecraft:worldgen/biome / betterend:old_bulbis_gardens]=net.minecraft.class_1959@498a3f1e}]
```

### Other Mods

BYG (Oh the Biomes you'll go), better nether and better end

**Comment by Rinigon** [comment] 2023-03-07 20:09
[New Text Document (2).txt](https://github.com/quiqueck/BetterEnd/files/10913585/New.Text.Document.2.txt)
 
here is my crash report

**Comment by NineLEL** [comment] 2023-03-11 18:38
I got the same issue.
**BetterEnd**
2.1.4

**BCLib**
2.1.6

**Fabric API**
0.75.1

**Fabric Loader**
0.14.17

**Minecraft**
1.19.2

Here's my log:

https://mclo.gs/MfEUKFc

**Comment by ambientNexus** [comment] 2023-03-12 06:41
Same issue here as well.

BetterEnd
2.1.4

BCLib
2.1.6

Fabric API
0.75.1

Fabric Loader
0.14.17

Minecraft
1.19.2

crashlog provided:
[crash-2023-03-11_22.36.45-server.txt](https://github.com/quiqueck/BetterEnd/files/10950139/crash-2023-03-11_22.36.45-server.txt)

Other mods: 
Terrablender 2.0.1.136
BYG 2.0.1.1
CorgiLib 1.0.0.32
Geckolib 3.1.40
Patchouli 77

**Comment by SHXRKIEgg** [comment] 2023-03-12 12:10
So I had these issues in BetterMC and MedievalMC and some reason just redoing the update fixed it for me. No idea why.

**Comment by mattwandcow** [comment] 2023-03-12 19:33
Our server had a the same issue:
`java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / betterend:chorus_forest]=net.minecraft.class_1959@5c7478}, Reference{ResourceKey[minecraft:worldgen/biome / betterend:old_bulbis_gardens]=net.minecraft.class_1959@3fb4046f}]`

According to the logs, a bat had fallen into the end portal and was trying to generate the end whenever a player logged in and loaded the Stronghold.

We disabled one of the triggering biomes in the biomes.json,the chorus_forest, deleted the end that had been generated, and moved the player away, and that resolved the issue for now

[crash-2023-03-12_09.58.59-server.txt](https://github.com/quiqueck/BetterEnd/files/10951798/crash-2023-03-12_09.58.59-server.txt)

**Comment by ghost** [comment] 2023-03-17 23:30
@mattwandcow I resolved this similarly. I have a question for you or for anyone that got this error. My game runs now with a newly generated end, however, this end does not contain any end cities. I tried using the /locate command to no avail, can you confirm if this is happening to you? 

Specifically in the log file I get this error: 
```
Couldn't load tag minecraft:has_structure/end_city as it is missing following references: betterend:chorus_forest (from worlds_together)
```

**Comment by fyretion** [comment] 2023-03-18 05:21
> Our server had a the same issue: `java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / betterend:chorus_forest]=net.minecraft.class_1959@5c7478}, Reference{ResourceKey[minecraft:worldgen/biome / betterend:old_bulbis_gardens]=net.minecraft.class_1959@3fb4046f}]`

I'm seeing the same issue, same biomes are supposedly the cause, game crash log: https://pastebin.com/hh0eCkMM

**Comment by quiqueck** [comment] 2023-06-19 22:20
Sorry for getting back late, but this issue should be fixed in the latest releases of BetterEnd.

**Closed as completed by quiqueck** 2023-06-19 22:20 UTC
