### ISSUE TITLE
[Bug] Server crashing whenever we try to explore end islands

### ISSUE THREAD

**Issue by Equatoiles** [quiqueck/BetterEnd#172] opened 2023-03-03 04:29 UTC
### What happened?

Every time we go to the end islands, the game lets us run around for a bit, and then the entire server crashes. After looking at the crash log and seeing what other people have said, ive found that the Ancient Emerald Ice block is causing some issue. Ive sent the crash log below

### BetterEnd

3.1.2

### BCLib

2.2.4

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 2023-03-02 23:20:32
Description: Exception ticking world

java.lang.ExceptionInInitializerError
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:particle_type / betterend:glowing_sphere])
	at net.minecraft.class_2370.method_40274(class_2370.java:135)
	at net.minecraft.class_2370.method_46744(class_2370.java:141)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:70)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:66)
	at org.betterx.betterend.registry.EndParticles.register(EndParticles.java:48)
	at org.betterx.betterend.registry.EndParticles.<clinit>(EndParticles.java:15)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Equatioles'/12, l='ServerLevel[world]', x=923.56, y=123.56, z=665.09]]
	Chunk stats: 2789
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-80,72,-16), Section: (at 0,8,0 in -5,4,-1; chunk contains blocks -80,0,-16 to -65,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 86041894 game time, 1625927 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 30931 (now: false), thunder time: 30677 (now: false)
	Known server brands: vanilla, Paper, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 5.15.83-1-pve
	Java Version: 17.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 1123373472 bytes (1071 MiB) / 4026531840 bytes (3840 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 124278.95
	Virtual memory used (MB): 108237.94
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 28.14
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx6144M -Xms3072M
	Fabric Mods: 
		alloy_forgery: Alloy Forgery 2.0.18+1.19.3
		appleskin: AppleSkin 2.4.2+mc1.19.3
			cloth-config: Cloth Config v9 9.0.94
				cloth-basic-math: cloth-basic-math 0.6.1
		architectury: Architectury 7.1.70
		auto-workstations: Auto Workstations v1.0-SNAPSHOT-20
		balm-fabric: Balm 5.0.2
		bclib: BCLib 2.2.4
		bettercombat: Better Combat 1.5.5+1.19.3
		betterend: Better End 3.1.2
		betternether: Better Nether 8.1.3
		betterthanmending: BetterThanMending 1.3.0
		bookshelf: Bookshelf 17.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.5.1-1.19.3
			maelstrom_library: Maelstrom Library 1.4-1.19.3-rc1
			multipart_entities: MultipartEntities 1.3-1.19.3-rc1
		capybara: Capybara 2.0.1
		carryon: Carry On 2.0.4.15
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		charmofundying: Charm of Undying 6.2.1+1.19.3
		chas: Craftable Horse Armour & Saddle 1.19-1.9-Fabric
		clumps: Clumps 9.0.0+16
		collective: Collective 6.43
		comforts: Comforts 6.1.1+1.19.3
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			spectrelib: SpectreLib 0.12.1+1.19.2
		copper_pipe: Simple Copper Pipes 1.12-1.19.3
		cosmetic-armor: Cosmetic Armor 1.4.1
		crawl: Crawl 0.11.5
			mm: Manningham Mills 2.3
		creativecore: CreativeCore (Fabric) 2.10.4
			net_minecraftforge_eventbus: eventbus 6.0.4
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		customizableelytra: Customizable Elytra 1.6.5-1.19.3
		darkpaintings: DarkPaintings 14.0.2
		dimdoors: DimensionalDoors 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.1.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		dragonloot: DragonLoot 1.1.3
		ecologics: Ecologics 2.1.12
		explorerscompass: Explorer's Compass 1.19.3-2.2.0-fabric
		fabric-api: Fabric API 0.72.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.4+1134c5b885
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.42+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.8+1134c5b885
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.3.0+85f102ee85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		forgeconfigapiport: Forge Config API Port 5.0.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.7.5
		geckolib: Geckolib 4.0.3
			com_eliotlash_mclib_mclib: mclib 20
		grassoverhaul: Grass Overhaul 23.2.1
		immersive_armors: Immersive Armors 1.5.4+1.19.3
		incantationem: Incantationem 1.2+1.19.3
			yet-another-config-lib: YetAnotherConfigLib 2.0.0
		ironchests: Iron Chests 1.7.8
			libgui: LibGui 6.5.0+1.19.3
				jankson: Jankson 5.0.0+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		itemphysic: ItemPhysic (Fabric) 1.6.7
		jamlib: JamLib 0.6.0+1.19.3
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 12.1.1.10
		kleeslabs: KleeSlabs 13.0.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lovely_snails: Lovely Snails 1.1.1+1.19.3
		magistuarmory: Epic Knights Mod 7.1
		mavapi: More Axolotl Variants API 1.0.3
		mavm: More Axolotl Variants Mod 1.2.1
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		midnightlib: MidnightLib 1.1.0
		minecraft: Minecraft 1.19.3
		more_babies: More Babies 1.0.1
		mru: Mineblock's Repetition Utilities 0.1.5+1.19.3
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mvs: Vanilla Structure Mod 2.5.12-1.19.3
		mythicmetals: Mythic Metals 0.17.1+1.19.3
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		naturescompass: Nature's Compass 1.19.3-2.1.1-fabric
		oldfishfarm: One Block Fish Farm 1.0.0
		oxidized: Oxidized 1.8.0
		player-animator: Player Animator 0.4.2+1.19.3
		quartzelv: Quartz Elevator 2.2.1+1.19
		randomshulkercolours: Random Shulker Colours 3.0
		redstonebits: Redstone Bits 1.10.0
		redstonepen: Redstone Pen 1.3.22
		repurposed_structures: Repurposed Structures 6.3.14+1.19.3-fabric
		rightclickharvest: Right Click Harvest 3.1.0+1.19.3
		simplyswords: Simply Swords 1.43.1-1.19.3
		soulsweapons: Marium's Soulslike Weaponry 0.9.8
		spark: spark 1.10.29
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spellbound_weapons_mr: Spellbound Weapons 4.0.1d
		stoneholm: Stoneholm 1.4.4
		t_and_t: Towns and Towers 1.10.1
			blue_endless_jankson: jankson 1.2.1
		terralith: Terralith 2.3
		things: Things 0.3.0+1.19.3
		travelersbackpack: Traveler's Backpack 1.19.3-8.3.2
		trinkets: Trinkets 3.5.1
		tumbleweed: Tumbleweed 0.5.2
		veinmining: Vein Mining 1.0.1+1.19.3
		villagernames: Villager Names 4.5.0
		voidtotem: Void Totem 2.2.0
		woof: Woof 3.0.0-1.19.3
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			owo: oωo 0.9.3+1.19.3
		worldedit: WorldEdit 7.2.13+46576cc
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		yigd: You're in Grave Danger 1.5.1
	Server Running: true
	Player Count: 1 / 48; [class_3222['Equatioles'/12, l='ServerLevel[world]', x=923.56, y=123.56, z=665.09]]
	Data Packs: vanilla, file/bukkit, dimdoors:classic, dimdoors:default, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Nitjsefnie** [comment] 2023-03-09 01:39
If you didn't manage to get a workaround yet, you can manually compile, without makeParticles code it works... until it hits another bug with different particles

**Comment by Nitjsefnie** [comment] 2023-03-09 01:43
Also probably same bug as https://github.com/quiqueck/BetterEnd/issues/171 https://github.com/quiqueck/BetterEnd/issues/167 https://github.com/quiqueck/BetterEnd/issues/143

**Comment by Equatoiles** [comment] 2023-03-09 09:48
what do you mean by manually compile? I'm not familiar with code much so I am not exactly sure what that means. Thank you for the help though

**Comment by AgentScar** [comment] 2023-03-11 23:14
> If you didn't manage to get a workaround yet, you can manually compile, without makeParticles code it works... until it hits another bug with different particles

how would I be able to manually compile? Or alternatively would you have a download?

**Comment by quiqueck** [comment] 2023-05-16 11:10
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:10 UTC
