### ISSUE TITLE
[Bug] Completely bonked chunk load-times when installed with terralith.

### ISSUE THREAD

**Issue by alkerss** [quiqueck/BetterEnd#122] opened 2022-12-02 02:25 UTC
### What happened?

Apologies for the cross-post on BCLib BetterNether and BetterEnd Github's. Did it, since I don't know where the issue lies.
And I would've informed Terralith as well, but they don't appear to have a Github issues page.

Trying to put a long story short. Many hours were spent debugging chunks loading incredibly slowly when flying around in creative. And I managed to narrow it down to BCLib + BetterNether + BetterEnd in combination with Terralith. 
I can't say where the issue lies exactly because the issue persisted with BCLib + BetterNether and BCLib + BetterEnd but not with just BCLib, though I'd assume that might be because BCLib isn't trying to do anything with biomes, perhaps, so even though the bug might be in BCLib, it doesn't show, since BN or BE aren't present *shrug*, but I digress.

I also tested combinations with BCLib + BetterNether and BetterEnd
+Incendium
+Nullscape
+Oh the Biomes you'll go
+Cinderscape
and maybe some others that I'm forgetting. But none of them have this issue, it was only Terralith. I also tested Terralith 2.3.3 and 2.3.4. The bulk of testing was with Terralith 2.3.5 however. but all had the same issue.
The issue even happens when just Terralith + BCLib + BE or BN are installed.

Anyway. Summary of the ISSUE:
Start game
Create a new world (default or BetterX, doesn't matter)
(In the Overworld) Creative fly with sprint and watch your chunk loading come to a crawl.
(For testing I used 8-chunk render distance and flew around at 200y every time and just flew in a straight line till approx 5000 blocks away from spawn for the sake of consistency.)

Without Terralith but with BCLib, BN + BE   OR   Without BCLib, BN + BE but with Terralith
The chunks simultaneously being loaded while flying full speed (with sprint) would never dip below 310chunks (max being around 330ish with 8render dist)
However, as soon as you load the full combo of Terralith + the B B B the chunks loaded would consistently 10/10 times tested start slowly but consistently drop from sitting at around 300 to 10 seconds later sitting around 260 to 10 seconds later 220 etc, etc and often bottoming out at around 60-80 at which point chunks rendered weren't even bellow the player but lagging behind.

Doubt this is relevant info, but in case it is.
PC specs:
2080ti
ryzen9 5950x
64gb ddr4
8GB allocated to the game (Yeah I know, too much, but I'm testing a modpack with 200-400 mods at any given time, so it needs it, and it didn't occur to me to reduce the ram to remove a variable during this testing.)

Apologies if anything comes off in a weird way. I'm quite frustrated after my many hours of debugging my modpack, and while I'm relieved to have finally figured it out definitively. I am very frustrated to find out that the issue is between Terralith and the Tripple B's. Neither of which I'm willing to put on the chopping block.

### BetterEnd

2.1.2

### BCLib

2.1.4

### Fabric API

0.66.0+1.19.2

### Fabric Loader

0.14.10

### Minecraft

1.19.2

### Other Mods

```shell
Terralith
```

**Comment by quiqueck** [comment] 2022-12-10 15:23
Duplicate of quiqueck/BCLib#61

**Closed as completed by quiqueck** 2022-12-10 15:23 UTC
Labels: 🥈 duplicate
