### ISSUE TITLE
[Bug] Mixin error on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [quiqueck/BetterEnd#52] opened 2022-07-26 06:52 UTC
### What happened?

Mixin error. Happens on Quilt, causes other mods to have issues

https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7

### BetterEnd

2.0.9

### BCLib

2.0.16

### Minecraft

1.19

### Relevant log output

```shell
https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7
```

### Other Mods

```shell
https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7
```

**Comment by quiqueck** [comment] 2022-07-26 12:15
Thanks for opening an Issue. From what I can see, this is caused by an interaction with another mod and is not a Quilt specific issue. 

Multiple mods appear to inject to the same method in the ModelBakery. Since we are processed second, the error just mentions our mod. I can try to change our Mixin, but that may not resolve the conflict...

**Comment by quiqueck** [comment] 2022-07-26 17:32
Might be fixed with 2.0.10.

**Comment by Sunconure11** [comment] 2022-07-26 19:46
Still present.

https://pastebin.com/fK1mJ0Cf

**Comment by quiqueck** [comment] 2022-07-26 19:52
The logs state that it is still BetterEnd 2.0.9 and bclib 2.0.16. Wrong logs?

**Comment by Sunconure11** [comment] 2022-07-26 19:55
Okay, looks like ATLauncher did not download it, then.

**Comment by Sunconure11** [comment] 2022-07-26 19:56
Wait, I'm wrong.

**Comment by Sunconure11** [comment] 2022-07-26 19:57
Unrelated mod erroring.

**Comment by Sunconure11** [comment] 2022-07-26 19:59
https://pastebin.com/Z5mLEq4W

Aaaand the crash that ended up leading me to deducing Better End as a cause of a potential error here came back.

**Comment by Sunconure11** [comment] 2022-07-26 20:01
Creeper Overhaul
Biome Makeover
Terrablender
Arcanus
Spoorn Pink
Spoorn Packs
Left Hanging
Reaping
MC Dungeons + Story suite
Requiem
Enhanced Block Entities
Better End?

These are the mods I went through, BTW, to find this mod as a possible error source.

**Comment by Sunconure11** [comment] 2022-07-26 20:02
https://pastebin.com/eqe3rC8Z

https://pastebin.com/3s2edtRz

https://pastebin.com/NCKULuSb

https://pastebin.com/8m8811wf

https://pastebin.com/dHELGFW2

https://gist.github.com/Sunconure11/fe55897fbe7e77d05dce12e5d8c1e14e

https://gist.github.com/Sunconure11/7abf61efa57e81f29264af29506bc074

https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7

Associated logs

**Comment by quiqueck** [comment] 2022-07-26 20:12
Unfortunately those logs are inconclusive as to what is the root cause. The only way to solve this is by disabling one mod at a time and testing if the crashes are still there. I know it is tedious, but in situations like this it is the only way.

I would however start with performance/non essential Mods like NotEnoughCrashes, DashLoader and so on.

**Comment by Sunconure11** [comment] 2022-07-27 00:18
I think it may have been enhanced block entities. Will test tomorrow.

**Comment by Sunconure11** [comment] 2022-07-27 04:50
The mod at fault is...

https://github.com/CammiePone/Arcanus

**Comment by Sunconure11** [comment] 2022-07-27 04:51
[crash logs.zip](https://github.com/quiqueck/BetterEnd/files/9195098/crash.logs.zip)

If you wanna see the logs that led me to this, here it is.

**Closed as completed** 2022-07-27 10:06 UTC
Labels: 🧱 external

**Comment by Sunconure11** [comment] 2022-07-27 11:08
This appears to be absent on smaller mod load orders.

**Comment by Sunconure11** [comment] 2022-07-27 11:12
If you can, see if you can go over Arcanus' code and see if they are doing something there.

**Comment by Sunconure11** [comment] 2022-07-27 11:16
https://gist.github.com/Sunconure11/58d82e41bddef982195cca3cc12ecdd7

Log of interest.

**Comment by Sunconure11** [comment] 2022-07-27 15:37
Are you using redirects?

https://github.com/ArtixAllMighty/HangMan/issues/11

**Comment by quiqueck** [comment] 2022-07-28 11:34
This is the log from the old version.

From what I have seen so far, the remaining issues have nothing to do with BetterEnd or BCLib. That is why I closed the issue. I also think that the issue Title over at Arcanus and HangMan is misleading, as this has nothing to do with BetterEnd.

Since Redirects are dangerous (they prevent other Mods from changing that logic), we use them sparingly. Currently only in the Class for the NetherPortal where we use it to allow Blocks other than Obsidian as Portal-Frames and when the list EditorPresets get's initialised to ensure that the List is mutable. 
Hard Errors with mixing (the ones that cause a crash) have a pretty clear log message that tells users that two redirects were attempted but failed. Other errors are soft-fails (where other mods try to modify the original behaviour but fail, since that behaviour is never called). Our redirects are carefully designed and deliberately chosen to prevent (or at least significantly lower the chance for) the later type of fail.

So again, as far as I can see, this is no longer related to BetterEnd.

**Comment by Sunconure11** [comment] 2022-07-28 11:36
I'll come back to this with new info once more mods update/properly mark themselves for 1.19.1. I cannot do more testing as a result.

**Comment by Sunconure11** [comment] 2022-07-28 11:38
I do have one candidate though, if you want to investigate the hunch. Immersive portals. Redirects are common there.

**Comment by quiqueck** [comment] 2022-07-28 11:50
I do test compat with Immersive portals (on fabric) on a regular basis. And as I said. Redirect-related crashes will show up with the mention of "redirect" in the logs :)
