### ISSUE TITLE
can't craft[Bug] 

### ISSUE THREAD

**Issue by TheWrongLuke** [quiqueck/BetterEnd#70] opened 2022-08-30 17:39 UTC
### What happened?

idk if it is only for me but neither singleplayer nor multiplayer i can't use the new ores for tools and armors

### BetterEnd

latest

### BCLib

latest

### Fabric API

latest

### Fabric Loader

latest

### Minecraft

1.19.1

### Other Mods

```shell
better nether, graves, REI
```

**Comment by fireheart3911** [comment] 2022-09-01 10:45
I have the same issue on 1.19(.0), seems like some stuff did not initialise on startup.
The following recipes are missing:
- Eternal Crystal
- Crystalite Armor
- Ender Shard? (The Thing you get when you put a pearl in an anvil)
- Everything involving infusuion crafting
- Everything involving smithing hammers
It also seems like eternal portals are not generating

Stuff i used:
- Mod Version 2.1.0
- Fabric 0.14.9
- latest BCLib 2.1.0
- Better Nether 7.1.0
- JEI 11.1.1.239

**Comment by StevenC21** [comment] 2022-09-16 05:46
I am able to find and activate eternal portals, although I similarly am unable to craft/infuse anything regarding the armor or others. Hopefully this will be fixed very soon!

Better End 2.1.0
Fabric 0.14.9
BCLib 2.1.0

**Comment by Andrew-Silver** [comment] 2022-09-18 12:57
All recepies involving smithing hammers are lost

**Comment by slimygs** [comment] 2022-09-19 19:24
I indeed am experiencing the same problem. Unable to craft new gear with anvils, smokers, etc. Basically can not go past netherite still.

**Comment by quiqueck** [comment] 2022-10-08 18:32
Duplicate of #64

**Closed as completed by quiqueck** 2022-10-08 18:32 UTC
