### ISSUE TITLE
[Bug] Particle-caused server crash

### ISSUE THREAD

**Issue by Nitjsefnie** [quiqueck/BetterEnd#176] opened 2023-03-09 01:48 UTC
### What happened?

Infusion Ritual particles crash the server.

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.75.1

### Fabric Loader

0.14.14

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Oops.

Time: 2023-03-08 22:02:47
Description: Ticking block entity

java.lang.ExceptionInInitializerError
	at org.betterx.betterend.particle.InfusionParticleType.<init>(InfusionParticleType.java:60)
	at org.betterx.betterend.rituals.InfusionRitual.tick(InfusionRitual.java:139)
	at org.betterx.betterend.blocks.entities.InfusionPedestalEntity.tickEntity(InfusionPedestalEntity.java:72)
	at net.minecraft.class_2818$class_5563.redirect$zkl000$checkProcessBEs(class_2818.java:783)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:472)
	at net.minecraft.class_3218.method_18765(class_3218.java:379)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.handler$zki000$modifiedRunLoop(MinecraftServer.java:4408)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:particle_type / betterend:glowing_sphere])
	at net.minecraft.class_2370.method_40274(class_2370.java:135)
	at net.minecraft.class_2370.method_46744(class_2370.java:141)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:70)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:66)
	at org.betterx.betterend.registry.EndParticles.register(EndParticles.java:48)
	at org.betterx.betterend.registry.EndParticles.<clinit>(EndParticles.java:15)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betterend.particle.InfusionParticleType.<init>(InfusionParticleType.java:60)
	at org.betterx.betterend.rituals.InfusionRitual.tick(InfusionRitual.java:139)
	at org.betterx.betterend.blocks.entities.InfusionPedestalEntity.tickEntity(InfusionPedestalEntity.java:72)
	at net.minecraft.class_2818$class_5563.redirect$zkl000$checkProcessBEs(class_2818.java:783)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:472)
	at net.minecraft.class_3218.method_18765(class_3218.java:379)

-- Block entity being ticked --
Details:
	Name: betterend:infusion_pedestal // org.betterx.betterend.blocks.entities.InfusionPedestalEntity
	Block: Block{betterend:infusion_pedestal}[has_item=true,has_light=false,state=default]
	Block location: World: (-975,75,835), Section: (at 1,11,3 in -61,4,52; chunk contains blocks -976,0,832 to -961,255,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Block: Block{betterend:infusion_pedestal}[has_item=true,has_light=false,state=default]
	Block location: World: (-975,75,835), Section: (at 1,11,3 in -61,4,52; chunk contains blocks -976,0,832 to -961,255,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:472)
	at net.minecraft.class_3218.method_18765(class_3218.java:379)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.handler$zki000$modifiedRunLoop(MinecraftServer.java:4408)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 2 total; [class_3222['kupouzar'/143, l='ServerLevel[New World]', x=-970.12, y=75.00, z=836.81], class_3222['Nitjsefnie'/5404, l='ServerLevel[New World]', x=-975.94, y=75.00, z=836.53]]
	Chunk stats: 3969
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (16,67,16), Section: (at 0,3,0 in 1,4,1; chunk contains blocks 16,0,16 to 31,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1515070 game time, 1515070 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 17111 (now: false), thunder time: 45629 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.handler$zki000$modifiedRunLoop(MinecraftServer.java:4408)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Linux (amd64) version 4.19.0-12-amd64
	Java Version: 17.0.6, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 3904727568 bytes (3723 MiB) / 5771362304 bytes (5504 MiB) up to 5771362304 bytes (5504 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
	Identifier: Intel64 Family 6 Model 44 Stepping 2
	Microarchitecture: Westmere (Server)
	Frequency (GHz): 2.67
	Number of physical packages: 2
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: MGA G200e [Pilot] ServerEngines (SEP1)
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x0522
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): -0.00
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): -0.00
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 48867.86
	Virtual memory used (MB): 16178.18
	Swap memory total (MB): 32757.00
	Swap memory used (MB): 78.75
	JVM Flags: 20 total; -Xms5500M -Xmx5500M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adapaxels: AdaPaxels 1.4.1+1.19.3
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.0.66
		baritone: Baritone 1.8.3-231-g7677ed82
		bclib: BCLib 2.2.4
		betterend: Better End 3.1.2
		betterfurnacesreforged: BetterFurnaces Reforged 1.19.3-0.2.1
		betternether: Better Nether 8.1.3
		betterthanmending: BetterThanMending 1.3.0
		bookshelf: Bookshelf 17.0.5
		botanypots: BotanyPots 10.0.3
		botanytrees: BotanyTrees 6.0.1
		bottleyourxp: Bottle Your Xp 3.1
		bundlesunlocked: Bundles Unlocked 1.0.6
		carpet: Carpet Mod 1.4.96+v230201
		chisel: Chisel Refabricated 1.4.5
		chunky: Chunky 1.3.53
		collective: Collective 6.48
		companion_bats: Companion Bats 1.19.2
			cloth-config: Cloth Config v9 9.0.94
				cloth-basic-math: cloth-basic-math 0.6.1
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		dimdoors: DimensionalDoors 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.1.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		dracomelette: Dracomelette 1.19-3
			midnightlib: MidnightLib 1.1.0
		dragonloot: DragonLoot 1.1.3
		dynview: Dynamic View Mod 1.19-3.2
		explorerscompass: Explorer's Compass 1.19.3-2.2.0-fabric
		extrasponges: ExtraSponges 1.4.2
		fabric-api: Fabric API 0.72.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.4+1134c5b885
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.42+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.8+1134c5b885
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.3.0+85f102ee85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabricloader: Fabric Loader 0.14.14
		factory_api: Factory API 1.19.3-0.1.6
			team_reborn_energy: Energy 2.3.0
		fallingtree: FallingTree 3.11.0
		fastload: Fast Load 2.6.11
		ferritecore: FerriteCore 5.1.0
		fwaystones: Fabric Waystones 3.0.7+mc1.19.3
		grindenchantments: Grind Enchantments 2.0.0+1.19.3
		hole_filler_mod: Hole Filler Mod 1.2.4
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.10.4
		mavapi: More Axolotl Variants API 1.0.3
		mavm: More Axolotl Variants Mod 1.2.1
		mcpitanlibarch: MCPitanLib 1.4.7-1.19.3-fabric
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		minecraft: Minecraft 1.19.3
		mining_dims: Mining Dimensions 1.5.7
			pugh_lib: Pugh Lib 1.5.6
		naturescompass: Nature's Compass 1.19.3-2.1.1-fabric
		nochatreports: No Chat Reports 1.19.3-v2.0.0
		owo: oωo 0.10.2+1.19.3
			blue_endless_jankson: jankson 1.2.1
		quickshulker: Quick Shulker 1.3.10-1.19.3
			kyrptconfig: Kyrpt Config 1.5.1-1.19.3
		reinfbarrel: Reinforced Barrels 2.3.3+1.19
		reinfchest: Reinforced Chests 2.3.1+1.19
			reinfcore: Reinforced Core 3.0.5+1.19
		reinfshulker: Reinforced Shulker Boxes 2.3.1+1.19
		respawningshulkers: Respawning Shulkers 3.3
		roughlyenoughitems: Roughly Enough Items 10.0.592
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.2.4+1.19.3
		smoothboot: Smooth Boot 1.19-1.7.1
		spawnermod: Enhanced Mob Spawners 1.2.3
		stacker: Stacker 3.0.2-1.19.3
			stacc: Stacc 1.4.0
		starlight: Starlight 1.1.1+fabric.ae22326
		taxfreelevels: Tax Free Levels 1.3.3
		toofast: TooFast 1.0.0
		toolleveling: ToolLeveling+ 1.19.3-1.4.3
		totw_additions: Towers of the Wild: Additions 1.2.4
		uncraftingtable76: Uncrafting Table 1.1.7
		upgradedshulkers: Upgraded Shulkers 1.1.3-1.19
			shulkerutils: shulkerutils 1.0.4-1.19
		veinmining: Vein Mining 1.0.1+1.19.3
			spectrelib: SpectreLib 0.12.1+1.19.2
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		xaerominimap: Xaero's Minimap 23.2.0
		xaeroworldmap: Xaero's World Map 1.29.2
		xps: Xp Obelisk 0.4.8-r+1.19.3-Fabric
	Server Running: true
	Player Count: 2 / 600; [class_3222['kupouzar'/143, l='ServerLevel[New World]', x=-970.12, y=75.00, z=836.81], class_3222['Nitjsefnie'/5404, l='ServerLevel[New World]', x=-975.94, y=75.00, z=836.53]]
	Data Packs: vanilla, fabric, dimdoors:classic, dimdoors:default, file/improvements (incompatible), file/minibossbars, file/Towers_Of_The_Wild_Reworked_v4.0.2_Fabric_Waystones
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by AgentScar** [comment] 2023-03-11 23:17
Would you happen to have a fix?

**Comment by u8Jj3** [comment] 2023-03-14 23:33
^Similar to that issue but with another effect related to particle. Crashed when I was exploring the world!

BetterEnd 3.1.2
BCLib 2.2.4
Quilted Fabric API 0.75.1
Quilt Loader 0.18.5
Minecraft 1.19.3
Relevant log output
https://mclo.gs/RkYB2ZA

**Comment by Nitjsefnie** [comment] 2023-03-15 00:00
@u8Jj3 https://github.com/quiqueck/BetterEnd/issues/172... Thanks for discovering issues on your own instead of posting on a random issue you find ^^

**Comment by u8Jj3** [comment] 2023-03-15 14:02
> @u8Jj3 #172... Thanks for discovering issues on your own instead of posting on a random issue you find ^^

That's not a "random issue" that's an issue with particle crashing the server, basically your issue with a "similar" crash log. I was not gonna create a duplicate issue just for this.

**Comment by Nitjsefnie** [comment] 2023-03-15 14:47
It is not triggered by the same code, therefore not a duplicate. However, if you used the gigantic search field in issues, you would find that your EXACT bug has already been reported in 4 different issues.

**Comment by ColdStoneSys** [comment] 2023-04-04 13:03
Having this same issue, as soon as I place the end crystal in the center the server dies and I get chunkbanned.

**Comment by quiqueck** [comment] 2023-05-16 11:10
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:10 UTC
