### ISSUE TITLE
[Bug] Server crashing  

### ISSUE THREAD

**Issue by Phlabry** [quiqueck/BetterEnd#143] opened 2023-02-04 16:54 UTC
### What happened?

server was working fine until i went in the end dimension. on the main island it didn't crash but as soon as I got to end islands it started to crash. I imported a new End dimension from another world to the server but it still crashes. 

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.73.2

### Fabric Loader

?

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-02-04 20:46:51
Description: Exception ticking world

java.lang.ExceptionInInitializerError
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:particle_type / betterend:glowing_sphere])
	at net.minecraft.class_2370.method_40274(class_2370.java:135)
	at net.minecraft.class_2370.method_46744(class_2370.java:141)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:70)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:66)
	at org.betterx.betterend.registry.EndParticles.register(EndParticles.java:48)
	at org.betterx.betterend.registry.EndParticles.<clinit>(EndParticles.java:15)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Phlabry'/110, l='ServerLevel[New World]', x=99872.63, y=100.00, z=999977.28]]
	Chunk stats: 1980
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (0,120,0), Section: (at 0,8,0 in 0,7,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2500023 game time, 2888360 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 142415 (now: false), thunder time: 17123 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.2.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2650849104 bytes (2528 MiB) / 4181721088 bytes (3988 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 19785.25
	Virtual memory used (MB): 17378.75
	Swap memory total (MB): 3468.99
	Swap memory used (MB): 110.55
	JVM Flags: 1 total; -Xmx8G
	Fabric Mods: 
		alloy_forgery: Alloy Forgery 2.0.18+1.19.3
		architectury: Architectury 7.0.66
		bclib: BCLib 2.2.4
		betterend: Better End 3.1.2
		betternether: Better Nether 8.1.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		dimdoors: DimensionalDoors 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.1.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		fabric-api: Fabric API 0.73.2+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.1+06937c4b85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.41+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.3+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+5b9a588b85
		fabricloader: Fabric Loader 0.14.13
		java: OpenJDK 64-Bit Server VM 18
		minecraft: Minecraft 1.19.3
		mythicmetals: Mythic Metals 0.17.0+1.19.3-ALPHA
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19.3
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		owo: oωo 0.9.3+1.19.3
			blue_endless_jankson: jankson 1.2.1
		roughlyenoughitems: Roughly Enough Items 10.0.586
			error_notifier: Error Notifier 1.0.9
	Server Running: true
	Player Count: 1 / 20; [class_3222['Phlabry'/110, l='ServerLevel[New World]', x=99872.63, y=100.00, z=999977.28]]
	Data Packs: vanilla, fabric, dimdoors:default, dimdoors:classic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
Better Nether
Alloy Forgery Mod
Mythic Metals
Roughly Enough Items
Dimensional Doors
```

**Comment by Smash-Creeper** [comment] 2023-02-05 19:51
Same thing happens to me :/
hoping this will help diagnose the problem easier

[crash-2023-02-05_02.41.32-server.txt](https://github.com/quiqueck/BetterEnd/files/10612008/crash-2023-02-05_02.41.32-server.txt)

**Comment by Hyacinyhdev** [comment] 2023-02-08 15:01
Same thing happens to me :(
[crash-2023-02-08_22.46.32-server.txt](https://github.com/quiqueck/BetterEnd/files/10686861/crash-2023-02-08_22.46.32-server.txt)

**Comment by TigerWalts** [comment] 2023-02-20 21:03
It looks like that on a server the BetterEnd particle types are being lazily registered at the point it needs to spawn one.

The particles are being registered when an EndParticles class is instantiated.

This is probably happening in a client-only codepath before the registry is frozen, but doesn't happen on a server until a particle needs to be spawned during the tick cycle.

**Comment by BrickOyster** [comment] 2023-02-23 20:23
I have the same problem 
Same exact error
Its the block Ancient emerald Ice trying to make particles

**Comment by exavian** [comment] 2023-03-27 01:15
This _seems_ to be the oldest issue reporting on this problem. Same error here as well.

Seems like this isn't the only particle that causes the problem as #176 shows a different particle triggering the same code to throw the same error.

It appears there's an attempt to load particles lazily which works on Singleplayer, but on a server the registry is frozen at that time.

**Comment by quiqueck** [comment] 2023-05-16 11:11
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:11 UTC
