### ISSUE TITLE
[Bug] Server crashes when player goes to end Islands

### ISSUE THREAD

**Issue by BrickOyster** [quiqueck/BetterEnd#167] opened 2023-02-23 22:49 UTC
### What happened?

same problem on Fabric
trying to figure out whats the exact reason 
Was traveling from x 0 z barely changed and ended up at x=-2305.97, y=103.69, z=-321.36
tell me what to send so you can see where I was close too (structure/biome)
The error message refers to src/main/java/org/betterx/betterend/blocks/AncientEmeraldIceBlock.java to the method makeParticles of AncientEmeraldIceBlock.java class with a null pointer exception
[crash-2023-02-23_22.44.23-server.txt](https://github.com/quiqueck/BetterEnd/files/10818336/crash-2023-02-23_22.44.23-server.txt)
refrence to method for whoever wants to see here
![image](https://user-images.githubusercontent.com/60844423/221027067-f94c9af3-81c1-4920-b1f3-58d3dd1a5397.png)

Ok edit:
I just replicated the crash in the overworld
I made a 2x2x1 anciendemeraldice pool and put 1 source block on it and it crashed with same error
![image](https://user-images.githubusercontent.com/60844423/221029390-41c4c41f-f467-4222-9f50-53418f54f3f2.png)

tried same think in singleplayer
didnt crash and I see the culprit I think freezing water making snow particles
![image](https://user-images.githubusercontent.com/60844423/221030494-b8318a19-75b0-44cd-bc7d-9c46c27ba76c.png)

server again
![image](https://user-images.githubusercontent.com/60844423/221031087-257be2ca-fe62-427f-aee6-0cb54f5ade1e.png)

after crash joined to this
![image](https://user-images.githubusercontent.com/60844423/221031377-b42e3cb8-56fa-494d-a6f4-23d2c6833041.png)
frozen water next to the emeraldice

and crashed shortly after

Hope this helps the developer

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.74.0

### Fabric Loader

0.14.15

### Minecraft

1.19.3

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-02-23 22:44:23
Description: Exception ticking world

java.lang.ExceptionInInitializerError
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:particle_type / betterend:glowing_sphere])
	at net.minecraft.class_2370.method_40274(class_2370.java:135)
	at net.minecraft.class_2370.method_46744(class_2370.java:141)
	at net.minecraft.class_2370.method_10272(class_2370.java:186)
	at net.minecraft.class_2378.method_39197(class_2378.java:118)
	at net.minecraft.class_2378.method_10230(class_2378.java:114)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:70)
	at org.betterx.bclib.particles.BCLParticleType.register(BCLParticleType.java:66)
	at org.betterx.betterend.registry.EndParticles.register(EndParticles.java:48)
	at org.betterx.betterend.registry.EndParticles.<clinit>(EndParticles.java:15)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.makeParticles(AncientEmeraldIceBlock.java:61)
	at org.betterx.betterend.blocks.AncientEmeraldIceBlock.method_9514(AncientEmeraldIceBlock.java:56)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:979)
	at net.minecraft.class_3218.method_18203(class_3218.java:512)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:322)

-- Affected level --
Details:
	All players: 1 total; [class_3222['BrickOyster'/201, l='ServerLevel[world]', x=-2283.70, y=138.64, z=-242.60]]
	Chunk stats: 2188
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (96,68,-256), Section: (at 0,4,0 in 6,4,-16; chunk contains blocks 96,0,-256 to 111,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 78526 game time, 78526 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 13835 (now: true), thunder time: 66432 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1589)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 19.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3127210776 bytes (2982 MiB) / 4294967296 bytes (4096 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e89
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34748.31
	Virtual memory used (MB): 29460.77
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 55.61
	JVM Flags: 2 total; -Xms4G -Xmx12G
	Fabric Mods: 
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.1.70
		bclib: BCLib 2.2.4
		betterend: Better End 3.1.2
		betternether: Better Nether 8.1.3
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		creativecore: CreativeCore (Fabric) 2.10.4
			net_minecraftforge_eventbus: eventbus 6.0.4
		fabric-api: Fabric API 0.74.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.0+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.14+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.5+1134c5b885
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.14.15
		java: Java HotSpot(TM) 64-Bit Server VM 19
		minecraft: Minecraft 1.19.3
		roughlyenoughitems: Roughly Enough Items 10.0.592
			error_notifier: Error Notifier 1.0.9
		skinrestorer: Skin Restorer 1.2.2
		travelersbackpack: Traveler's Backpack 1.19.3-8.3.2
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		vanillatweaks: VanillaTweaks 1.5.64
	Server Running: true
	Player Count: 1 / 20; [class_3222['BrickOyster'/201, l='ServerLevel[world]', x=-2283.70, y=138.64, z=-242.60]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Other Mods

```shell
appleskin-fabric-mc1.19.3-2.4.2
architectury-7.1.70-fabric
better-nether-8.1.3
cardinal-components-api-5.1.0
cloth-config-9.0.94-fabric
CreativeCore_FABRIC_v2.10.4_mc1.19.3
RoughlyEnoughItems-10.0.592
skin-restorer-1.2.2
travelers-backpack-1.19.3-8.3.2
VanillaTweaks-fabric-1.19.3-1.5.64
```

**Comment by quiqueck** [comment] 2023-05-16 11:10
Duplicate of #205

**Closed as completed by quiqueck** 2023-05-16 11:10 UTC
