### ISSUE TITLE
Betterx world customization settings sets default average biome size to 16 blocks in the GUI, and possibly makes biome gen that small by default. [Bug]

### ISSUE THREAD

**Issue by MCCrafter247** [quiqueck/BetterEnd#84] opened 2022-10-03 16:58 UTC
### What happened?

When going to the customization settings for the betterx world type, the average biome size settings are all set to 16 by default.

![unknown](https://user-images.githubusercontent.com/108512960/193631351-3a0ed2dd-5af8-4b57-b61f-9f215bd00856.png)

This is what it looks like by default. Given that these settings are meant to be for the number of blocks, and not chunks, this size is incredibly small. Paulevs over on the Discord confirmed this to be a GUI bug.

Something that I have been experiencing however, is that when I leave betterx on default settings, my biomes are all incredibly small and mixing together in weird blotches.

![2022-10-03_11 04 23](https://user-images.githubusercontent.com/108512960/193631934-8814f8d8-f181-4510-9318-42edddf0f70e.png)

![2022-10-03_11 04 03](https://user-images.githubusercontent.com/108512960/193632075-83c21142-2819-4581-97a9-e9ece46c6b31.png)

This is made even more obvious when loaded beside other mods that add in end biomes. The above pictures were with only the better end mod and it's requirements.

![2022-10-03_09 32 05](https://user-images.githubusercontent.com/108512960/193632261-e523191e-8d79-42f7-b418-47fcf83eeff1.png)

This is including Enderscape, Nullscape, and Oh the Biomes You'll Go. With more biomes, each individual biome generating on the default settings gets even smaller, becoming less like small, uneven blotches, and more like tiny cubes that are a fraction of a chunk in size. This makes the issue much more obvious. I don't know for sure if the GUI bug and this generation bug are related, but both of these seem to be abnormally small when the settings are first generated. It is like this for every world I've tried making. I've also deleted the mod configs before making a new world, just in case that would have an impact.

The only workaround I've found is to manually increase the biome sizes in the settings before making the world. This means in order to make the sizes normal on a server, I have to manually edit the biome sizes in the level.dat file.

![2022-10-03_12 53 09](https://user-images.githubusercontent.com/108512960/193634441-d0714401-8e05-4f1e-b41f-6a52df0b3c2f.png)

This is after manually adjusting the values to 256, which paulev said was the intended default size. So it's not that generation is breaking, it's that it is defaulting to a value that is incredibly small - way smaller than it should be.

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.62.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

### Relevant log output

```shell
No known relevant log output
```

### Other Mods

```shell
The default GUI average biome size settings are 16 blocks even when Better End, Fabric api, and bclib are the only mods present.

The same occurs with just these three mods for the small biome generation I've been experiencing, when no changes have been made to the customization settings. Though it is made more obvious when other end biome mods are present, such as nullscape, Oh the Biomes You'll Go, and Enderscape.

Also, this was in Minecraft version 1.19.2. The bug report wouldn't let me select that version for some reason.
```

**Comment by quiqueck** [comment] 2022-10-08 18:34
Duplicate of #80

**Closed as completed by quiqueck** 2022-10-08 18:34 UTC
