### ISSUE TITLE
[Bug] Nonfunctional Eternal Portal

### ISSUE THREAD

**Issue by alerikaisattera** [quiqueck/BetterEnd#118] opened 2022-11-22 16:43 UTC
### What happened?

An Eternal portal that does not work. After activating, portal blocks appear but passing through them does nothing. Other portals in the world work fine.

Seed: -2267580158807957166

Coordinates: -3968,83,-1968

### BetterEnd

2.1.1

### BCLib

2.1.3

### Fabric API

0.67.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Other Mods

```shell
- additionalentityattributes 1.0.0+1.19 via spectrum
	- advanced_reborn 1.1.2
	- ae2 12.8.5
	- alwaysawitherskull-fabric 2.0
	- amethyst_core 0.4.1+1.19 via amethyst_imbuement
	- amethyst_imbuement 1.19-19
	- architectury 6.3.49
	- autoconfig1u 3.4.0 via advanced_reborn
	- bclib 2.1.3
	- beaconoverhaul 1.7.3+1.19.2
	- betterend 2.1.1
	- betternether 7.1.2
	- blast 1.10
	- blue_endless_jankson 1.2.1 via owo
	- cardinal-components-base 5.0.1 via the_bumblezone
	- cardinal-components-entity 5.0.1 via the_bumblezone
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- collective-fabric 5.11
	- com_github_llamalad7_mixinextras 0.1.1-rc.4 via amethyst_imbuement
	- cryingghasts-fabric 2.0
	- darkloot 1.0.7
	- endportalrecipe-fabric 4.1
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.67.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.11+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.19+3dd584b490 via fabric-api
	- fabric-block-api-v1 1.0.0+12bfe4ea90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.21+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.2+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.36+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.4.2+6064db2a90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.0+ad31814d90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.5.1+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.30+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.6.0+fa140d5990 via fabric-api
	- fabric-item-groups-v0 0.3.34+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.22+aaaf9d3390 via fabric-api
	- fabric-keybindings-v0 0.2.20+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.5+kotlin.1.7.20
	- fabric-lifecycle-events-v1 2.2.1+9244241690 via fabric-api
	- fabric-loot-api-v2 1.1.8+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.11+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.19+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.18+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.6+9244241690 via fabric-api
	- fabric-networking-v0 0.3.23+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.1+06e0e25190 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-registry-sync-v0 0.9.27+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.0.13+12bfe4ea90 via fabric-api
	- fabric-renderer-indigo 0.6.15+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.21+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.16+12bfe4ea90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-rendering-v0 1.1.24+df3654b390 via fabric-api
	- fabric-rendering-v1 1.11.0+73145abb90 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.0+f9594cb690 via fabric-api
	- fabric-screen-api-v1 1.0.28+28270f5890 via fabric-api
	- fabric-screen-handler-api-v1 1.3.2+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.0+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.21+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.2+cd10d4fc90 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fake-player-api 0.5.0 via the_bumblezone
	- fiber 0.23.0-2 via collective-fabric
	- flowstone 4.0.0+1.19
	- fwaystones 3.0.5+mc1.19.2
	- gearreborn 1.19-0.1.15
	- gobber2 2.6.54
	- incubus_core 1.7.0 via spectrum
	- indium 1.0.9+mc1.19.2
	- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
	- iris 1.4.0
	- java 18
	- lithium 0.10.0
	- mcpitanlibarch 1.1.8-1.19-fabric
	- midnightlib 0.6.0 via the_bumblezone
	- minecraft 1.19.2
	- modmenu 4.0.6
	- netherwardblock 1.19.2-6
	- no-telemetry 1.4.0
	- noindium 1.1.0+1.19 via ae2
	- nopwp 2.1.0
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- owo 0.8.5+1.19
	- patchouli 1.19-73-FABRIC via amethyst_imbuement
	- phosphor 0.8.1
	- playerabilitylib 1.6.0 via amethyst_imbuement
	- programmerartinjector 1.2.1 via spectrum
	- pugh_lib 1.4.15 via gobber2
	- pugh_tools 1.3.22 via gobber2
	- reach-entity-attributes 2.3.0 via spectrum
	- reborncore 5.3.4 via techreborn
	- revelationary 1.0.2
	- roughlyenoughitems 9.1.555
	- satin 1.9.0 via spectrum
	- sodium 0.4.4+build.18
	- spectrum 1.5.7-1.19.2-magic
	- step-height-entity-attribute 1.0.0 via spectrum
	- structurized-reborn 1.19-01 via amethyst_imbuement
	- team_reborn_energy 2.2.0 via techreborn
	- techreborn 5.3.4
	- the_bumblezone 6.3.1+1.19.2
	- theprinter 1.0.2+1.19
	- toolleveling 1.19.2-1.4.1
	- trinkets 3.4.0 via amethyst_imbuement
```

**Comment by quiqueck** [comment] 2022-12-10 16:14
duplicate of #60

**Comment by quiqueck** [comment] 2022-12-10 16:15
Thank you very much :)

**Closed as completed** 2022-12-11 11:00 UTC
Labels: 🥈 duplicate
