### ISSUE TITLE
[Crash] Fail to startup - 1.19 Quilt

### ISSUE THREAD

**Issue by IgiariValkyr** [quiqueck/BetterEnd#18] opened 2022-06-23 06:46 UTC
### What happened?

Fails to start up with the Quilt Modloader

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.1 - Quilt

### Fabric Loader

0.14.7 - Quilt

### Minecraft

1.19

### Relevant log output

```shell
[01:41:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/DarkW/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Quilt Env=CLIENT
[01:41:04] [main/INFO]: Compatibility level set to JAVA_17
[01:41:05] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[01:41:05] [main/INFO]: tf.ssf.sfort.invisframes successfully loaded config file
[01:41:05] [main/WARN]: Reference map 'axolotl-item-fix-refmap.json' for axolotlitemfix.mixins.json could not be read. If this is a development environment you can ignore this message
[01:41:05] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 2 override(s) found
[01:41:05] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[01:41:05] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/biome/TheEndBiomeData$Overrides (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/biome/TheEndBiomeData$Overrides)
[01:41:05] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.biome.TheEndBiomeData$Overrides was not found bclib.mixins.common.json:TheEndBiomeDataMixin
[01:41:05] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[01:41:05] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[01:41:06] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[01:41:06] [main/WARN]: Error loading class: net/coderbot/iris/layer/IrisRenderTypeWrapper (java.lang.ClassNotFoundException: net/coderbot/iris/layer/IrisRenderTypeWrapper)
[01:41:06] [main/WARN]: @Mixin target net.coderbot.iris.layer.IrisRenderTypeWrapper was not found mixins.satin.client.json:iris.IrisRenderLayerWrapperMixin
[01:41:08] [main/WARN]: Discarding @Unique public method getAnimatedSkin in entityculling.mixins.json:DonorAbstractClientPlayerMixin because it already exists in net.minecraft.class_742
[01:41:11] [main/INFO]: Building unoptimized datafixer
[01:41:12] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[01:41:12] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[01:41:12] [main/ERROR]: Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/biome/TheEndBiomeData
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.17.1-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.1-beta.4.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/biome/TheEndBiomeData
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.getBiomes(BCLibEndBiomeSource.java:204) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:82) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:78) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.levelgen.LevelGenUtil.getBCLEndLevelStem(LevelGenUtil.java:80) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.createEndStem(BCLWorldPresetSettings.java:107) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildDimensionMap(BCLWorldPresetSettings.java:85) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildPreset(BCLWorldPresetSettings.java:71) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.lambda$static$0(BCLWorldPresets.java:32) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.bootstrapPresets(BCLWorldPresets.java:101) ~[bclib-2.0.5.jar:?]
	at net.minecraft.class_5317$class_7146.modify$bem000$bcl_getOverworldStem(class_5317.java:571) ~[client-intermediary.jar:?]
	at net.minecraft.class_5317$class_7146.method_41600(class_5317.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_5317.method_41593(class_5317.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) ~[quilt-loader-0.17.1-beta.4-1.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.1-beta.4.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.biome.TheEndBiomeData
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) ~[quilt-loader-0.17.1-beta.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.getBiomes(BCLibEndBiomeSource.java:204) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:82) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.generator.BCLibEndBiomeSource.<init>(BCLibEndBiomeSource.java:78) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.api.v2.levelgen.LevelGenUtil.getBCLEndLevelStem(LevelGenUtil.java:80) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.createEndStem(BCLWorldPresetSettings.java:107) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildDimensionMap(BCLWorldPresetSettings.java:85) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresetSettings.buildPreset(BCLWorldPresetSettings.java:71) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.lambda$static$0(BCLWorldPresets.java:32) ~[bclib-2.0.5.jar:?]
	at org.betterx.bclib.presets.worldgen.BCLWorldPresets.bootstrapPresets(BCLWorldPresets.java:101) ~[bclib-2.0.5.jar:?]
	at net.minecraft.class_5317$class_7146.modify$bem000$bcl_getOverworldStem(class_5317.java:571) ~[client-intermediary.jar:?]
	at net.minecraft.class_5317$class_7146.method_41600(class_5317.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_5317.method_41593(class_5317.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:154) ~[quilt-loader-0.17.1-beta.4-1.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.1-beta.4.jar:?]
	... 2 more
```

### Other Mods

```shell
- alternate-current 1.4.0
	- appleskin 2.4.0+mc1.19
	- architectury 5.7.28
	- axolotlitemfix 1.1.3
	- badpackets 0.1.2
	- balm-fabric 4.2.0+0
	- bclib 2.0.5
	- betterend 2.0.2
	- betterf3 1.3.1
	- betternether 7.0.2
	- blast 1.10
	- blue_endless_jankson 1.2.1
	- bookshelf 14.0.3
	- borderlessmining 1.1.4+1.19
	- cacao 1.2
	- cardinal-components-base 5.0.0-beta.1
	- cardinal-components-entity 5.0.0-beta.1
	- cardinal-components-world 5.0.0-beta.1
	- carpet 1.4.79
	- chat_heads 0.6.0
	- cloth-basic-math 0.6.1
	- cloth-config 7.0.72
	- clumps 9.0.0+3
	- com_electronwill_night-config_core 3.6.5
	- com_electronwill_night-config_toml 3.6.5
	- com_eliotlash_mclib_mclib 18
	- com_eliotlash_molang_molang 18
	- com_github_llamalad7_mixinextras 0.0.11
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT
	- com_typesafe_config 1.4.1
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- controlling 10.0+1
	- copper_pipe 1.10
	- couplings 1.9.0+1.19
	- crawl 0.11.0
	- croptopia 2.0.5
	- crowdin-translate 1.4+1.19
	- damagetilt 1.19-fabric-0.1.2
	- disable_custom_worlds_advice 3.0
	- easierchests 1.19-fabric0.53.3-1.7.0
	- easiervillagertrading 1.19-fabric0.53.3-1.5.4
	- effective 1.2.2
	- enchancement 1.19-1
	- enchdesc 11.0.4
	- entityculling 1.5.2-mc1.19
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fallingleaves 1.12.1+1.19
	- farmersdelight 1.19-0.3.0
	- ferritecore 4.2.1
	- fiber 0.23.0-2
	- forgottenrecipes 1.19-1.0.0
	- gbfabrictools 1.3.4+1.19
	- geckolib3 3.1.4
	- hardcore_torches 1.19-1.5
	- horsestatsvanilla 4.2.1
	- illuminations 1.10.6
	- impaled 1.1.4
	- indium 1.0.6+mc1.19
	- invisframes 2.1.1
	- io_leangen_geantyref_geantyref 1.3.11
	- iris 1.2.5
	- jankson 4.1.1+j1.2.1
	- java 17
	- krypton 0.2.0
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- libgui 6.0.0-beta.5+1.19-pre1
	- libninepatch 1.1.0
	- lithium 0.8.0
	- mason 1.1.3
	- mcwbridges 2.0.3
	- mcwdoors 1.0.6
	- mcwfences 1.0.5
	- mcwlights 1.0.3
	- mcwpaths 1.0.0
	- mcwroofs 2.1.2
	- mcwtrpdoors 1.0.5
	- mcwwindows 2.0.3
	- midnightlib 0.5.2
	- minecraft 1.19
	- mm 2.3
	- modmenu 4.0.0
	- mousetweaks 2.22
	- netherportalfix 10.0.0
	- notenoughanimations 1.6.0
	- org_anarres_jcpp 1.4.14
	- org_joml_joml 1.10.4
	- org_json_json 20211205
	- org_spongepowered_configurate-core 4.1.2
	- org_spongepowered_configurate-hocon 4.1.2
	- patchouli 1.19-72-FABRIC
	- pickyourpoison 1.0.9
	- pride 1.1.2+1.19
	- quilt_base 2.0.0-beta.5+1.19
	- quilt_biome 2.0.0-beta.5+1.19
	- quilt_block_extensions 2.0.0-beta.5+1.19
	- quilt_client_command 2.0.0-beta.5+1.19
	- quilt_command 2.0.0-beta.5+1.19
	- quilt_crash_info 2.0.0-beta.5+1.19
	- quilt_dimension 2.0.0-beta.5+1.19
	- quilt_item_group 2.0.0-beta.5+1.19
	- quilt_item_setting 2.0.0-beta.5+1.19
	- quilt_lifecycle_events 2.0.0-beta.5+1.19
	- quilt_loader 0.17.1-beta.4
	- quilt_networking 2.0.0-beta.5+1.19
	- quilt_recipe 2.0.0-beta.5+1.19
	- quilt_registry 2.0.0-beta.5+1.19
	- quilt_registry_entry_attachments 2.0.0-beta.5+1.19
	- quilt_resource_loader 2.0.0-beta.5+1.19
	- quilt_screen 2.0.0-beta.5+1.19
	- quilt_tags 2.0.0-beta.5+1.19
	- quilt_tooltip 2.0.0-beta.5+1.19
	- quilted_fabric_api 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_api_base 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_api_lookup_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_biome_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_blockrenderlayer_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_command_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_command_api_v2 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_commands_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_containers_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_content_registries_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_convention_tags_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_crash_report_info_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_dimensions_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_entity_events_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_events_interaction_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_events_lifecycle_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_game_rule_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_item_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_item_groups_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_key_binding_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_keybindings_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_lifecycle_events_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_loot_api_v2 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_loot_tables_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_message_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_mining_level_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_models_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_networking_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_networking_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_object_builder_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_particles_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_registry_sync_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_renderer_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_renderer_indigo 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_renderer_registries_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_rendering_data_attachment_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_rendering_fluids_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_rendering_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_rendering_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_resource_conditions_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_resource_loader_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_screen_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_screen_handler_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_textures_v0 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_transfer_api_v1 2.0.0-alpha.4+0.56.1-1.19
	- quilted_fabric_transitive_access_wideners_v1 2.0.0-alpha.4+0.56.1-1.19
	- ratsmischief 1.3.8
	- reach-entity-attributes 2.3.0
	- respawnablepets 1.19-2
	- roughlyenoughitems 9.0.491
	- satin 1.8.0
	- scout 1.0.0
	- sit 1.19-20
	- sodium 0.4.2+build.16
	- sound_physics_remastered 1.19-1.0.6
	- spark 1.9.13
	- spelunker 1.5.0
	- spruceui 4.0.0+1.19
	- step-height-entity-attribute 1.0.0
	- stoneholm 1.4.4
	- tooltipfix 1.0.5-1.19
	- trinkets 3.4.0
	- trulytreasures 1.19-2.0.2
	- tweed4_data 1.2.1
	- tweed4_data_hjson 1.1.0
	- villager-hats 1.4.1
	- voicechat 1.19-2.2.45
	- wthit 5.4.3
```

**Comment by frankbauer** [comment] 2022-06-24 10:08
Duplicate of quiqueck/BCLib#2

**Comment by quiqueck** [comment] 2022-06-24 10:08
Duplicate of quiqueck/BCLib#2

**Closed as completed by quiqueck** 2022-06-24 10:08 UTC
Labels: 🥈 duplicate
